### PR TITLE
fix n+1 queries issue in supervisors#index and supervisors#datatable

### LINKED ISSUE #5890: fix SupervisorsController#index N+1 issues
## What type(s) of user does this feature affect?
 - supervisors
 - admins
 - volunteers

## Description

This controller action has issues with N+1 queries (method call makes an additional method call for each item it finds.) 

You can see these in our scout: https://scoutapm.com/shares/25925ed7-ff6a-4ec3-b590-976cd36de2d3

Go through all the methods to ensure all the needed data is preloaded in the first query and no additional calls to the database need to be made.

## N+1 Resources

- sample PR https://github.com/rubyforgood/casa/pull/5868
- https://guides.rubyonrails.org/active_record_querying.html#eager-loading-associations
- https://medium.com/doctolib/how-to-find-fix-and-prevent-n-1-queries-on-rails-6b30d9cfbbaf
- https://github.com/flyerhzm/bullet?tab=readme-ov-file#log

## How to access the QA site
_Login Details:_  
[Link to QA site](https://casa-qa.herokuapp.com/)  

Login Emails: 
- volunteer1@example.com  view site as a volunteer
- supervisor1@example.com view site as a supervisor
- casa_admin1@example.com view site as an admin
- all_casa_admin1@example.com view site as an all casa admin
  - go to `/all_casa_admins/sign_in`  

password for all users: 12345678  

### Questions? Join Slack!

We highly recommend that you join us in [slack](https://join.slack.com/t/rubyforgood/shared_invite/zt-21pyz2ab8-H6JgQfGGI0Ab6MfNOZRIQA) #casa channel to ask questions quickly. And [discord](https://discord.gg/qJcw2RZH8Q) for office hours (currently Tuesday 5-7pm Pacific), stakeholder news, and upcoming new issues.

### LINKED ISSUE #5891: fix SupervisorsController#datatable N+1 issues
## What type(s) of user does this feature affect?
 - supervisors
 - admins
 - volunteers

## Description

This controller action has issues with N+1 queries (method call makes an additional method call for each item it finds.) 

You can see these in our scout: https://scoutapm.com/shares/cd70c473-d304-4df7-84e1-1b7c519aa4e9

Go through all the methods to ensure all the needed data is preloaded in the first query and no additional calls to the database need to be made.

## N+1 Resources

- sample PR https://github.com/rubyforgood/casa/pull/5868
- https://guides.rubyonrails.org/active_record_querying.html#eager-loading-associations
- https://medium.com/doctolib/how-to-find-fix-and-prevent-n-1-queries-on-rails-6b30d9cfbbaf
- https://github.com/flyerhzm/bullet?tab=readme-ov-file#log

## How to access the QA site
_Login Details:_  
[Link to QA site](https://casa-qa.herokuapp.com/)  

Login Emails: 
- volunteer1@example.com  view site as a volunteer
- supervisor1@example.com view site as a supervisor
- casa_admin1@example.com view site as an admin
- all_casa_admin1@example.com view site as an all casa admin
  - go to `/all_casa_admins/sign_in`  

password for all users: 12345678  

### Questions? Join Slack!

We highly recommend that you join us in [slack](https://join.slack.com/t/rubyforgood/shared_invite/zt-21pyz2ab8-H6JgQfGGI0Ab6MfNOZRIQA) #casa channel to ask questions quickly. And [discord](https://discord.gg/qJcw2RZH8Q) for office hours (currently Tuesday 5-7pm Pacific), stakeholder news, and upcoming new issues.

### PR DESCRIPTION
**Pull request by guswhitten**
### What github issue is this PR for, if any?
Resolves #5890 
Resolve #5891 

### What changed, and _why_?
Fixes the N+1 issues for the Supervisors#index and Supervisors#datatable. Does this by preloading any record associations that are used later on.

### Screenshots please :)
`supervisors#index` before
casa-5891-index-before

`supervisors#index` after
casa-5891-index-after

`supervisors#datatable` before
casa-5890-datatable-before

`supervisors#datatable` after
casa-5890-datatable-after

### CODE REVIEW

File: app/controllers/supervisors_controller.rb [hunk 1]
```diff
@@ -12,7 +12,10 @@ class SupervisorsController < ApplicationController
 
   def index
     authorize Supervisor
-    @supervisors = policy_scope(current_organization.supervisors)
+    @supervisors = policy_scope(current_organization.supervisors).includes(
```
Comment (elasticspoon) [inline app/controllers/supervisors_controller.rb:15]: Do you know what this policy scope is adding to the query? could we move the includes? or is it reused elsewhere where the preloading isn't needed?

Comment (guswhitten) [reply app/controllers/supervisors_controller.rb]: good call. if i understood you correctly, i moved the `.includes` to the specific block in the .html.erb where the `volunteers` and other relations are accessed

Comment (guswhitten) [reply app/controllers/supervisors_controller.rb:15]: i'm not sure about the policy_scope. i did not see other uses of `@supervisors` atm. is there a place you think itd be better to move it to?

Comment (elasticspoon) [reply app/controllers/supervisors_controller.rb:15]: I'm not making a suggestion I was just posing another angle that you might consider, since it might be less code duplication.

You could move the includes bits to https://github.com/rubyforgood/casa/blob/main/app/policies/supervisor_policy.rb and have something like https://github.com/rubyforgood/casa/blob/4d0d12f7eb4d40f6b823d3d8d42300c736be233c/app/policies/hearing_type_policy.rb#L2 in there.

**Review by elasticspoon — APPROVED** [review]
LGTM! Thanks! This was a 3 year old N+1 issue I believe :)
