### PR TITLE
fix non-volunteer-cant-save-address-new-case

### LINKED ISSUE #3971: Bug: Non Volunteer Users Can't Save a Volunteer Address In a New Case Contact
### Impacted User Types
 - supervisors
 - admins

### Current Behavior
If a user that isn't a volunteer tries to make a new case contact and tries to fill out driving reimbursement with an address, the address doesn't save.

### Expected Behavior
The address saves.

### How to Replicate
ex: 
1. - Log into staging as an admin or supervisor.
2. - Navigate to a casa case.
3. - Click the button to make a new case contact.
4. - Fill out all the required fields.
5. - Select Yes for driving reimbursement
6. - Fill out driving reimbursement with a volunteer address and a number of miles(now required)

### QA Login Details:
[Link to QA site](https://casa-qa.herokuapp.com/)  

Login Emails: 
- volunteer1@example.com  view site as a volunteer
- supervisor1@example.com view site as a supervisor
- casa_admin1@example.com view site as an admin

password for all users: 12345678  

### Questions? Join Slack!

We highly recommend that you join us in slack https://rubyforgood.herokuapp.com/ #casa channel to ask questions quickly and hear about office hours (currently Tuesday 6-8pm Pacific), stakeholder news, and upcoming new issues.

### PR DESCRIPTION
**Pull request by italomatos**
### What github issue is this PR for, if any?
Resolves #3971

### What changed, and why?
It was fixed a bug when try to create a new casa contact, and fill voluteers address.

### How will this affect user permissions?
- Supervisor permissions:
- Admin permissions:

### How is this tested? (please write tests!) 💖💪
- Log into staging as an admin or supervisor.
- Navigate to a casa case.
- Click the button to make a new case contact.
- Fill out all the required fields.
- Select Yes for driving reimbursement
- Fill out driving reimbursement with a volunteer address and a number of miles(now required)

### CODE REVIEW

File: app/controllers/case_contacts_controller.rb [hunk 1]
```diff
@@ -161,7 +160,9 @@ def create_case_contact_for_every_selected_casa_case(selected_cases)
         new_cc = casa_case.case_contacts.create(create_case_contact_params.except(:casa_case_attributes))
       end
 
-      if @selected_cases.count == 1 && @case_contact.valid?
+      case_contact = @case_contact.dup
```
Comment (compwron) [inline app/controllers/case_contacts_controller.rb:163]: dup?

**Review by compwron — APPROVED** [review]
