### PR TITLE
Fix admin change password bug

### LINKED ISSUE #2352: Admin cannot change password
### Impacted User Types
 - admins

### Environment
Production 

### Current Behavior
When attempting to change a password, the password change fails and an error screen is shown.
Updating password

### Expected Behavior
When I attempt to change my password it should change my password.

### How to Replicate

1. - Log in as an admin.
2. - Click on "Edit Profile" in the left sidebar menu.
3. - Click the "Change Password" button at the bottom of the page.
4. - Enter the existing password and new password into the appropriate textboxes.
5. - Click the "Update Password" button at the bottom of the page.
Screen Shot 2021-08-02 at 7 43 39 PM

```
Aug 02 19:13:08 casa-production app/web.1 I, [2021-08-03T02:13:08.758412 #4]  INFO -- [Bugsnag]: [43526069-b404-4790-8f84-3281cc057d7a] Notifying https://notify.bugsnag.com of NoMethodError
Aug 02 19:13:08 casa-production app/web.1 F, [2021-08-03T02:13:08.762047 #4] FATAL -- : [43526069-b404-4790-8f84-3281cc057d7a]   
Aug 02 19:13:08 casa-production app/web.1 [43526069-b404-4790-8f84-3281cc057d7a] ActionView::Template::Error (undefined method `length' for nil:NilClass):
Aug 02 19:13:08 casa-production app/web.1 [43526069-b404-4790-8f84-3281cc057d7a]     27:         </button>
Aug 02 19:13:08 casa-production app/web.1 [43526069-b404-4790-8f84-3281cc057d7a]     28: 
Aug 02 19:13:08 casa-production app/web.1 [43526069-b404-4790-8f84-3281cc057d7a]     29:         <% if policy(CasaAdmin).see_deactivate_option? %>
Aug 02 19:13:08 casa-production app/web.1 [43526069-b404-4790-8f84-3281cc057d7a]     30:           <% if @active_casa_admins.length > 1 %>
Aug 02 19:13:08 casa-production app/web.1 [43526069-b404-4790-8f84-3281cc057d7a]     31:             <%= link_to "Deactivate",
Aug 02 19:13:08 casa-production app/web.1 [43526069-b404-4790-8f84-3281cc057d7a]     32:                         deactivate_casa_admin_path(current_user),
Aug 02 19:13:08 casa-production app/web.1 [43526069-b404-4790-8f84-3281cc057d7a]     33:                         method: :patch,
Aug 02 19:13:08 casa-production app/web.1 [43526069-b404-4790-8f84-3281cc057d7a]   
Aug 02 19:13:08 casa-production app/web.1 [43526069-b404-4790-8f84-3281cc057d7a] app/views/users/edit.html.erb:30
Aug 02 19:13:08 casa-production app/web.1 [43526069-b404-4790-8f84-3281cc057d7a] app/views/users/edit.html.erb:5
Aug 02 19:13:08 casa-production app/web.1 [43526069-b404-4790-8f84-3281cc057d7a] app/controllers/users_controller.rb:32:in `update_password'
```

### PR DESCRIPTION
**Pull request by efgalvao**
### What github issue is this PR for, if any?
Resolves #2352 

### What changed, and why?
Added to the controller the active_casa_admin so the view can render normally.

### How will this affect user permissions?
It will not

### How is this tested? (please write tests!) 💖💪
Now there are 2 tests to check if an admin can change passwod

### Screenshots please :)
* Showing errors for admin:

Screenshot from 2021-08-06 16-02-53

* Showing  success message:

Screenshot from 2021-08-06 16-03-26

### Feelings gif (optional)
What gif best describes your feeling working on this issue? https://giphy.com/
efgalvao

### CODE REVIEW

File: spec/system/users/edit_spec.rb [hunk 1]
```diff
@@ -71,5 +71,28 @@
...
+      fill_in "Password", with: "123"
+      fill_in "Password Confirmation", with: "1234"
+
+      click_on "Update Password"
+
+      expect(page).to have_text("Password confirmation doesn't match Password")
+      expect(page).to have_text("Password is too short (minimum is 6 characters)")
+    end
+
+    it "display sucesscfull message when admin update password" do
```
Comment (compwron) [inline spec/system/users/edit_spec.rb:87]: typo in "sucesscfull" please fix

**Review by compwron — APPROVED** [review]
very cool :) Yay tests!!!

File: spec/system/users/edit_spec.rb (hunk 1 above)
Comment (efgalvao) [reply spec/system/users/edit_spec.rb]: Fixed.

**Review by compwron — APPROVED** [review]
