### PR TITLE
Fix: Load wrong casa cases when editing volunteer

### LINKED ISSUE #1959: Cases from wrong org shown on Edit Volunteer case assignment
### Impacted User Types
admins and supervisors

### Environment
all

### Current Behavior
shows cases not allowed

### Expected Behavior
show only cases for org

### How to Replicate
Screen Shot 2021-04-16 at 5 37 04 PM (1)

### PR DESCRIPTION
**Pull request by hiendinhngoc**
### What github issue is this PR for, if any?
Resolves #1959 

### What changed, and why?
- Update `actively_assigned_excluding_volunteer` scope, add where condition to load only casa cases which have the same casa organization with the volunteer.

### How will this affect user permissions?
- Supervisor permissions:
- Admin permissions:

### CODE REVIEW

File: app/models/casa_case.rb [hunk 1]
```diff
@@ -53,6 +53,7 @@ class CasaCase < ApplicationRecord
     joins(:case_assignments)
       .where(case_assignments: {active: true})
       .where.not(case_assignments: {volunteer: volunteer})
+      .where(casa_org: volunteer.casa_org)
```
Comment (compwron) [inline app/models/casa_case.rb:56]: This is great! Please remove the other changes (javascript and package.json) and add a test for this so we don't break it again :)

**Review by compwron — CHANGES_REQUESTED** [review]

File: app/models/casa_case.rb (hunk 1 above)
Comment (hiendinhngoc) [reply app/models/casa_case.rb:56]: sorry I missed the message, although the code was merged, I will add the test when I have time, thanks for reviewing.
