### PR TITLE
[#3822] Fix ambiguous CaseContact column reference

### LINKED ISSUE #3822: Fix prod bug with filters
```
[Bugsnag](https://app.slack.com/team/B019LV4HDUY)
APP  [9:06 AM](https://rubyforgood.slack.com/archives/C010Z8RK8E6/p1660061211595709)
New unhandled error in production from [casa](https://app.bugsnag.com/ruby-for-good/casa?i=sk&m=nw) in case_contacts#index [(details)](https://app.bugsnag.com/ruby-for-good/casa/errors/62f2861ba2dde50009f83bb7?event_id=62f2861b009621ac68570000&i=sk&m=nw)

Unhandled error
ActiveRecord::StatementInvalid: PG::AmbiguousColumn: ERROR:  column reference "name" is ambiguous
LINE 1: ...8/09') AND (occurred_at >= '2022/04/01') ORDER BY "name" ASC
                                                            ^
Location
app/controllers/case_contacts_controller.rb:22 - group_by
```

url like `https://casavolunteertracking.org/case_contacts?filterrific%5Boccurred_starting_at%5D=2022%2F04%2F01&filterrific%5Boccurred_ending_at%5D=2022%2F08%2F09&filterrific%5Bcontact_type%5D%5B%5D=24&filterrific%5Bcontact_medium%5D=&filterrific%5Bwant_driving_reimbursement%5D=&filterrific%5Bcontact_made%5D=&filterrific%5Bsorted_by%5D=contact_type_asc&commit=Filter`

### How to Replicate
ex: 
1. - Log into staging as an admin or supervisor.
2. - Click on "Generate Reports" in the left sidebar menu.
3. - Filter by a volunteer who has logged at least one case contact.
4. - Click "Generate report" at the bottom of the page.

### QA Login Details:
[Link to QA site](https://casa-qa.herokuapp.com/)  

Login Emails: 
- volunteer1@example.com  view site as a volunteer
- supervisor1@example.com view site as a supervisor
- casa_admin1@example.com view site as an admin

password for all users: 12345678  

### Questions? Join Slack!

We highly recommend that you join us in slack https://rubyforgood.herokuapp.com/ #casa channel to ask questions quickly and hear about office hours (currently Tuesday 6-8pm Pacific), stakeholder news, and upcoming new issues.

### PR DESCRIPTION
**Pull request by ATMartin**
### What github issue is this PR for, if any?
Resolves #3822

### What changed, and why?
Previously, when sorting `CaseContact`s by their `ContactType`, the `order(:name)` query created an ambiguous reference. This change ensures the `order` specifically targets the `contact_types` table, removing ambiguity and making sure we can filter when we'd like.

### How will this affect user permissions?
- Volunteer permissions: *N/A*
- Supervisor permissions: *N/A*
- Admin permissions: *N/A*

### How is this tested? (please write tests!) 💖💪
Controller tests are extended to verify the failing filter requests are now fixed.

### Screenshots please :)
_Not much to show here, but this is verification that the example failing URL from #3822 is now loading as expected! 🙌_
image

### Feelings gif (optional)
Person in bright colors exclaiming "Boy, how the tables have turned"

### CODE REVIEW

File: app/models/case_contact.rb [hunk 1]
```diff
@@ -102,7 +102,7 @@ class CaseContact < ApplicationRecord
     when /^occurred_at/
       order(occurred_at: direction)
     when /^contact_type/
-      joins(:contact_types).order(name: direction)
+      joins(:contact_types).merge(ContactType.order(name: direction))
```
Comment (ATMartin) [inline app/models/case_contact.rb:105]: This is a little fancier than the simpler `order("contact_types.name #{direction}")`, but ensures we're using everything ActiveRecord gives us when building the query.

File: spec/controllers/case_contacts_controller_spec.rb [hunk 2]
```diff
@@ -25,6 +25,45 @@
     allow(controller).to receive(:current_user).and_return(volunteer)
   end
 
+  describe "GET index" do
```
Comment (ATMartin) [inline spec/controllers/case_contacts_controller_spec.rb:28]: I used these tests to identify exactly where the bug was coming from, so they're scoped broadly. Only the "returns filtered case contacts by contact type" test is truly required to verify behavior here, BUT the `index` route wasn't tested at all so I left the bit of extra coverage for good measure. 🔮 🤞

**Review by compwron — APPROVED** [review]
very nice! :)
