### PR TITLE
Turn off auto width for case contacts dataTable

### LINKED ISSUE #1038: Case Contacts page text is not vertically aligned correctly when the window is wide
**What is the problem, and what should happen instead?**

On the Case Contacts page, when the window is wide, the data is not vertically aligned with the column headings. It shifts to the right. To reproduce, log in to dev seeded application as volunteer1@example.com (you can use `bin/login 1` to do this), select "Case Contacts", and increase window width continuously until you see this effect.

**Screenshots of current behavior, if any**

image

### PR DESCRIPTION
**Pull request by carterrwood**
### What github issue is this PR for, if any?

Resolves #1038 

### What changed, and why?

Our data tables were calculating the wrong width. Overwriting those classes width's to be `100%` made them render as expected. 

-- Another way we could fix this is by turning the autoWidth function off, just like how we're doing in `dashboard.js` to the `volunteersTable`. However if we do this, the table doesn't scale when shrinking and expanding the window.

### How will this affect user permissions?
- Volunteer permissions:
- Supervisor permissions:
- Admin permissions:

### How is this tested? (please write tests!) 💖💪

Added a test to make sure both the `case-contact-table`'s have the same width. 

### Screenshots please :)

image
Scaled
image

### Feelings gif (optional)
alt text

### CODE REVIEW

**Review by compwron — APPROVED** [review]
Yay! Sometimes the smallest piece of code makes a big difference :) 
I see that this PR is in "draft" state so I will not merge it yet. When you are ready for final review set it to "ready for review" instead of draft. :)

**Comment by carterrwood** [comment]
> Yay! Sometimes the smallest piece of code makes a big difference :)
> I see that this PR is in "draft" state so I will not merge it yet. When you are ready for final review set it to "ready for review" instead of draft. :)

Yes indeed! You saw my previous changes but they didn't scale the table when the page changed sizes, which strategy do you think is better?

**Comment by compwron** [comment]
Scaling the table on size change is preferrable

**Comment by carterrwood** [comment]
Should be good to go then! 😄

File: spec/system/admin_views_case_contact_index_spec.rb [hunk 1]
```diff
@@ -0,0 +1,22 @@
...
+    admin = create(:casa_admin, casa_org: organization)
+    sign_in admin
+
+    visit case_contacts_path
+
+    table_header = all('.case-contacts-table').first
+    table_body = all('.case-contacts-table').last
+    expect(table_header['style']).to have_text table_body['style']
+
+    # Resize page and check again
```
Comment (compwron) [inline spec/system/admin_views_case_contact_index_spec.rb:18]: very very nice :)

**Review by compwron — APPROVED** [review]

**Comment by compwron** [comment]
You are invited to the CASA asynchronous retrospective-and-futurespective! Please take a look at https://bit.ly/casaretro (no login required) and add at least one note! Even if it's just "I was here and you are cool" or "omg y'all why do you keep messaging me" we want to hear it. <3
Next week Wednesday 18 November @ 6pm Pacific time we will Zoom about the board and talk about themes and takeaways. (Zoom link in our calendar at http://bit.ly/casacal or slack #casa channel https://rubyforgood.herokuapp.com/ )
Please ESPECIALLY add lots of notes if you won't be able to make it on Wednesday to talk!
* Note: the board will be monitored for spam; message me or any team lead if you see a problem
https://bit.ly/casaretro
