### PR TITLE
error when admin imports inactive casa_case

### LINKED ISSUE #1190: error when admin attempts to import inactive casa_case
dependent on #1182

AS an **admin**,
WHEN I attempt to import an inactive `casa_case`,
I _do not_ want the `casa_case` to be re-imported, 
_instead_, I WANT to receive an informative error message,
SO THAT I understand why the inactive `casa_case` was not imported.

### How it works now
`casa_cases` currently only have one state, which is active, but #1182 is changing that – soon, `casa_cases` will have two states: active or inactive.

### How it should work
When an admin attempts to import an _inactive_ `casa_case` which is already in the system, the inactive `casa_case` should not be imported. Instead, a reason why that row of the import failed should be listed in the "Errors" column available for download after an import attempt.

That error should read something like:
_CASA case already exists, but is inactive. Reactivate the CASA case instead._

### PR DESCRIPTION
**Pull request by steph-hickman9**
An additional check was made to provide a different error
message to an admin importing an existing case that is
inactive. This Provides more useful information than just telling
them that the case already exists.

Tests were added to ensure that the error message renders correctly.

### What github issue is this PR for, if any?
Resolves #1190 

### What changed, and why?
An additional check was made to provide a different error
message to an admin importing an existing case that is
inactive. This provides more useful information than just telling
them that the case already exists.

### How will this affect user permissions?
- Volunteer permissions:
- Supervisor permissions:
- Admin permissions:

### How is this tested? (please write tests!) 💖💪
Tests were added to ensure that the error message renders correctly.

### Screenshots please :)
Screen Shot 2020-10-28 at 12 43 16 PM

### Feelings gif (optional)
What gif best describes your feeling working on this issue? https://giphy.com/
How to embed:
gif

### CODE REVIEW

File: spec/requests/imports_request_spec.rb [hunk 1]
```diff
@@ -120,6 +122,59 @@
...
+          }
+      }.to change(CasaCase, :count).by(0)
+
+      expect(request.session[:import_error]).to include("Not all rows were imported.")
+      expect(request.session[:exported_rows]).to include("Case CINA-00-0000 already exists, but is inactive. Reactivate the CASA case instead.")
+      expect(response).to redirect_to(imports_url(import_type: "casa_case"))
+    end
   end
 end
 # TODO: dominique test for message success/fail
```
Comment (compwron) [inline spec/requests/imports_request_spec.rb:180]: @dominiquecuevas I think you missed a spot :)

**Review by compwron — APPROVED** [review]
Looks great! And yay tests!!!!

**Comment by compwron** [comment]
The linter is mad. I'm going to just merge it and then fix the lint.

**Comment by compwron** [comment]
You are invited to the CASA asynchronous retrospective-and-futurespective! Please take a look at https://bit.ly/casaretro (no login required) and add at least one note! Even if it's just "I was here and you are cool" or "omg y'all why do you keep messaging me" we want to hear it. <3
Next week Wednesday 18 November @ 6pm Pacific time we will Zoom about the board and talk about themes and takeaways. (Zoom link in our calendar at http://bit.ly/casacal or slack #casa channel https://rubyforgood.herokuapp.com/ )
Please ESPECIALLY add lots of notes if you won't be able to make it on Wednesday to talk!
* Note: the board will be monitored for spam; message me or any team lead if you see a problem
https://bit.ly/casaretro
