### PR TITLE
unescape page body for string comparison

### LINKED ISSUE #4683: Bug: HTML Escape flaky test
### Current Behavior
An apostrophe in a name results in the HTML escaped version of the name being displayed which is what we want. The test for the display however does not expect the HTML escaped version. Make the test expect the HTML escaped version.

The test can be found at `spec/requests/volunteers_spec.rb` on line 110

Example Output:  

```
Failures:

  1) /volunteers GET /edit shows correct supervisor options
     Failure/Error: supervisors.each { |supervisor| expect(paspec/requests/volunteers_spec.rb:110ge).to include(supervisor.display_name) }

       expected "<!DOCTYPE html>\n<html>\n<head>\n  <title>CASA Volunteer Tracking</title>\n\n  \n  \n\n  <meta name=...l\">SMS Terms &amp; Conditions</a>\n    </span>\n  </span>\n</footer>\n\n</div>\n</body>\n</html>\n" to include "Nicolas O'Kon"
       Diff:
       @@ -1,293 +1,585 @@
       -Nicolas O'Kon
       +<!DOCTYPE html>
       +<html>
       +<head>spec/requests/volunteers_spec.rb:110
       +  <title>CASA Volunteer Tracking</title>
       +
       +  
       +  
       +
       +  <meta name="description" content="Volunteer activity tracking for CASA volunteers, supervisors, and administrators.">
       +  <meta name="viewport" content="width=device-width,initial-scale=1">
       +
       +  <meta property="og:title" content="CASA Volunteer Tracking">
       +  <meta property="og:description" content="Volunteer activity tracking for CASA volunteers, supervisors, and administrators.">
       +  <meta property="og:url" content="http://www.example.com/">
       +  <meta property="og:image" content="http://www.example.com/assets/login-fa5a101a63c8827f12a91ebbac10f6577d91b6d3dc84de579acf2eff477bfc7d.jpg">
       +
       +  <link rel="apple-touch-icon" type="image/x-icon" href="/assets/apple-icon-57x57-99eab95725d4b5cb923317a8dc1f4e6bdc959cecdf3b5a5d25d2fd5fa7d7e264.png" sizes="57x57" />
       +<link rel="apple-touch-icon" type="image/x-icon" href="/assets/apple-icon-60x60-837d7a074aec0c8bf24d67262494e17ea86911cbf1a94628ff42646c9da9d7d6.png" sizes="60x60" />
       +<link rel="apple-touch-icon" type="image/x-icon" href="/assets/apple-icon-72x72-fb24a90476081de29a65aee438467b6e4385ec8e51ef1ce0ba053491981324ce.png" sizes="72x72" />
       +<link rel="apple-touch-icon" type="image/x-icon" href="/assets/apple-icon-76x76-8cbc7596302ca9152ca84106577522ec114661ae82b88d04e9df534501726746.png" sizes="76x76" />
       +<link rel="apple-touch-icon" type="image/x-icon" href="/assets/apple-icon-114x114-09b7deba68c41bfc4c45845da64817bd195f7949e53ee94c4e9c738f6d31a948.png" sizes="114x114" />
       +<link rel="apple-touch-icon" type="image/x-icon" href="/assets/apple-icon-120x120-cf7b6593721f679b589e2c371160e56d445b9d52e012fa26fcba0b13611e8447.png" sizes="120x120" />
       +<link rel="apple-touch-icon" type="image/x-icon" href="/assets/apple-icon-144x144-ba1cd68311398a1ca9edc47400b9beae97a50d7e3e00c12dc341a70ebfbb6923.png" sizes="144x144" />
       +<link rel="apple-touch-icon" type="image/x-icon" href="/assets/apple-icon-152x152-b2cd52aa45ee76e428c87e27b7a1c5f00fcb657988ce2276f7da3c9fce21de87.png" sizes="152x152" />
       +<link rel="apple-touch-icon" type="image/x-icon" href="/assets/apple-icon-180x180-bd7c7b2b3cb9ee8330436768709c326a95170ef72be30b4b5ec4e025f07087a3.png" sizes="180x180" />
       +<link rel="icon" type="image/png" href="/assets/android-icon-192x192-e9f0a988ce4e63ec0a81034e884e711f8136b9a7d99225913a2f622a57d14bb7.png" sizes="192x192" />
       +<link rel="icon" type="image/png" href="/assets/favicon-32x32-9a91f30ee37faa81c9e092612a0f101dee43c56fe4cd7b3c8195c494ae307210.png" sizes="32x32" />
       +<link rel="icon" type="image/png" href="/assets/favicon-96x96-b34be23cf8ee8417b73f45ff161da2598a2446628fa76805e92937a18b9cd9c1.png" sizes="96x96" />
       +<link rel="icon" type="image/png" href="/assets/favicon-16x16-8520149c92cb0e0b0637e56c359201033e0717d9675c41c3d4c08a86fbcee6b7.png" sizes="16x16" />
       +<meta name="msapplication-TileColor" content="#ffffff">
       +<meta name="msapplication-TileImage" content="/assets/ms-icon-144x144-ba1cd68311398a1ca9edc47400b9beae97a50d7e3e00c12dc341a70ebfbb6923.png">
       +<meta name="theme-color" content="#ffffff">
       +
       +
       +  <script src="/assets/application-835a43a11d112910eb3a037f3df72155ba41953fec3562964490a6bb29c7db78.js" data-turbo-track="reload" defer="defer"></script>
       +  <link rel="stylesheet" href="/assets/application-3e0eee36f8626ef0b614447d861c2145df1d957fe7613fe29ae761ebbabcae6e.css" data-turbo-track="reload" />
       +
       +  <style>
       +    /* Override one of fontawesome's style rules to link fonts with fingerprinted file names */
       +    @font-face {
       +      font-family: 'Font Awesome 6 Free';
       +      font-style: normal;
       +      font-weight: 900;
       +      font-display: $fa-font-display;
       +      src: url('/assets/fa-solid-900-342a65c5fc675ba7ab8c0c6c7781e87b647b25eb7a7f126e8f3c8e5362327d03.woff2') format('woff2'),
       +        url('/assets/fa-solid-900-c5f0df81045a248b9ef094f1352137231cb441c51f5f88ecbed36a3fa130e18b.ttf') format('truetype');
       +    }
       +  </style>
       +</head>
       +<body class="volunteers volunteers-edit">
       +  <noscript>
       +    <div>
       +      <h2>
       +        Please enable javascript
       +      </h2>
       +      <p>
       +        This app requires javascript to work
       +      </p>
       +    </div>
       +  </noscript>
       +  <nav class="navbar mobile">
       +  <img sizes="72x72" rel="icon" type="image/png" class="mobile-icon" src="/assets/icon-logo-8bd5ebedc49ef88ae2c767f2b1b0fc80ac56f82715628f9a9d28b013719a7736.png" />
       +  <button id="toggle-sidebar-js" type="button" class="btn btn-outline-light">
       +    Menu
       +  </button>
### How to Replicspec/requests/volunteers_spec.rb:110
       +</nav>
       +
       +  <div id="sidebar-js" class="sidebar-wrapper">
       +  <div class="sidebar-heading text-center">
       +      <a href="/"><img id="casa-logo" alt="CASA Logo" class="d-inline-block align-text-bottom" src="/assets/default-logo-ac9c000520f1459dfdb8c6f7e463cfa2c05236d955c3e1d0625c8c8fb9b6fdac.png" /></a>
       +  </div>
       +  <div class="sidebar-container">
       +    <div class="sidebar-menu">
       +      <div class="list-group list-group-flush">
       +          <a class="list-group-item " href="/notifications">Inbox</a>
       +          <a class="list-group-item " href="/supervisors">Supervisors</a>
       +          <a class="list-group-item active" href="/volunteers">Volunteers</a>
       +          <a class="list-group-item " href="/other_duties">Other Duties</a>
       +          <a class="list-group-item " href="/casa_cases">Cases</a>
       +          <a class="list-group-item " href="/casa_admins">Admins</a>
       +      </div>
       +    </div>
       +    <div class="sidebar-footer">
       +      <div class="list-group list-group-flush account-details">
       +        <li class="list-group-item">
       +          <span class="label">Location</span>
       +          <span class="value">CASA Org 911</span>
       +        </li>
       +        <li class="list-group-item">
       +          <span class="label">Role</span>
       +          <span class="value">Casa Admin</span>
       +        </li>
       +      </div>
       +      <div class="list-group list-group-flush footer-nav">
       +          <a class="list-group-item" href="/users/edit">Edit Profile</a>
       +            <a class="list-group-item" href="/case_court_reports">Generate Court Reports</a>
       +            <a class="list-group-item" href="/reimbursements">Reimbursement Queue</a>
       +            <a class="list-group-item" href="/reports">Export Data</a>
       +            <a class="list-group-item" href="/imports">System Imports</a>
       +            <a class="list-group-item" href="/mileage_rates">Mileage Rates</a>
       +            <a class="list-group-item" href="/casa_org/854/edit">Edit Organization</a>
       +          <li class="list-group-item">
       +            <strong>User 1091</strong>
       +            email1300@example.com
       +          </li>
       +        <a class="list-group-item" href="/users/sign_out">Log out</a>
       +        <div id="mobile-space"></div>
       +      </div>
       +    </div>
       +  </div>
       +</div>
       +
       +  <div class="footer container-fluid">
       +    <div class="content">
       +      <div class="header-flash">
       +</div>
       +
       +      <a href="/volunteers">Back</a>
       +
       +<div class="row">
       +  <div class="col-sm-12 form-header">
       +    <h1>Editing Volunteer</h1>
       +    <form id="cc-check" action="/volunteers/1056/reminder" accept-charset="UTF-8" method="post"><input type="hidden" name="_method" value="patch" autocomplete="off" />
       +  <input type="submit" name="commit" value="Send Reminder" class="btn btn-primary casa-case-button" id="reminder_button" data_toggle="tooltip" title="Remind volunteer to input case contacts" data-disable-with="Send Reminder" />
       +<label class="unbold" for="with_cc">
       +  <input type="checkbox" name="with_cc" id="with_cc" value="1" />
       +  Send CC to Supervisor and Admin
       +</label>
       +</form>
       +  </div>
       +  <div class="col-sm-12 form-header">
       +    <a class="btn btn-primary casa-case-button" href="/volunteers/1056/impersonate">Impersonate</a>
       +  </div>
       +</div>
       +<div class="card card-container">
       +  <div class="card-body">
       +    <form class="edit_volunteer" id="edit_volunteer_1056" action="/volunteers/1056" accept-charset="UTF-8" method="post"><input type="hidden" name="_method" value="patch" autocomplete="off" />
       +      
       +
       +      <div class="field form-group">
       +  <label for="volunteer_email">Email</label>
       +    <input class="form-control" type="text" value="email1304@example.com" name="volunteer[email]" id="volunteer_email" />
       +</div>
       +
       +<div class="field form-group">
       +  <label for="volunteer_display_name">Display name</label>
       +    <input class="form-control" type="text" value="Usespec/requests/volunteers_spec.rb:110r 1092" name="volunteer[display_name]" id="volunteer_display_name" />
       +</div>
       +
       +<div class="field form-group">
       +  <label for="volunteer_phone_number">Phone number</label>
       +    <input class="form-control" type="text" value="" name="volunteer[phone_number]" id="volunteer_phone_number" />
       +</div>
       +  <div class="field form-group">
       +    <label for="volunteer_address">Mailing address</label>
       +      
       +        <input class="form-control" type="text" name="volunteer[address_attributes][content]" id="volunteer_address_attributes_content" />
       +  </div>
       +
       +
       +      <div>
       +  <span class="font-weight-bold">CASA organization </span>
       +  CASA Org 908
       +</div>
       +<div>
       +  <span class="font-weight-bold">Added to system </span>
       +  January 30, 2023
       +</div>
       +<div>
       +  <span class="font-weight-bold">Invitation email sent </span>
       +  never
       +</div>
       +<div>
       +  <span class="font-weight-bold">Last logged in </span>
       +  never
       +</div>
       +<div>
       +  <span class="font-weight-bold">Invitation accepted </span>
       +  never
       +</div>
       +<div>
       +  <span class="font-weight-bold">Password reset last sent </span>
       +  never
       +</div>
       +
       +  <div>
       +    <span class="font-weight-bold">Learning Hours This Year</span>
       +    0h 0min
       +  </div>
       +
       +
       +      <p>
       +        <div class="field form-group">
       +    Volunteer is <span class="badge badge-success text-uppercase display-1">Active</span><br>
       +      <a class="btn btn-outline-danger" data-confirm="WARNING: Marking a volunteer inactive will make them unable to login. Are you sure you want to do this?" rel="nofollow" data-method="patch" href="/volunteers/1056/deactivate">Deactivate volunteer</a>
       +    <a class="btn btn-outline-danger" href="/volunteers/1056/resend_invitation">Resend Invitation (Email)</a>
       +    <a class="btn btn-outline-danger" href="/volunteers/1056/send_reactivation_alert">Send Reactivation Alert (SMS)</a>
       +</div>
       +
       +      </p>
       +
       +      <div class="actions">
       +        <input type="submit" name="commit" value="Submit" class="btn btn-primary" data-disable-with="Submit" />
       +      </div>
       +</form>  </div>
       +</div>
       +
       +<div class="notes">
       +  <h1 class="pt-5">Notes</h1>
       +
       +  <div class="card card-container">
       +    <div class="card-body">
       +      <br>
       +      <form id="volunteer-note-form" action="/volunteers/1056/notes" accept-charset="UTF-8" method="post">
       +        <h3>Create a New Note</h3>
       +        <div class="form-group">
       +          <textarea rows="5" placeholder="Enter a note regarding the volunteer. These notes are only visible to CASA administrators and supervisors." class="form-control" name="note[content]" id="note_content">
       +</textarea>
       +        </div>
       +
       +        <div class="actions">
       +          <input type="submit" name="commit" value="Save Note" class="btn btn-primary" id="note-submit" data-disable-with="Save Note" />
       +        </div>
       +</form>    </div>
       +  </div>
       +</div>
       +
       +
       +<div>
       +  <h1 class="pt-5">Manage Cases</h1>
       +
       +  <div class="card card-container">
       +    <div class="card-body">
       +
       +        <br>
       +
       +        <h3>Assign a New Case</h3>
       +
       +        <form class="new_case_assignment" id="new_case_assignment" action="/case_assignments?volunteer_id=1056" accept-charset="UTF-8" method="post">
       +
       +          <div class='form-group'>
       +            <label for='case_assignment_casa_case_id'>Select a Case</label>
       +            <select class="form-control select2" name="case_assignment[casa_case_id]" id="case_assignment_casa_case_id"><optgroup label="Not Assigned"></optgroup><optgroup label="Assigned"></optgroup></select>
       +          </div>
       +
       +          <input type="submit" name="commit" value="Assign Case" class="btn btn-primary" data-disable-with="Assign Case" />
       +</form>    </div>
       +  </div>
       +</div>
       +
       +<div>
       +  <h1 class="pt-5">Manage Supervisor</h1>
       +
       +  <div class="card card-container">
       +    <div class="card-body">
       +      <br>
       +        <h3>Assign a Supervisor</h3>
       +        <form class="new_supervisor_volunteer" id="new_supervisor_volunteer" action="/supervisor_volunteers?volunteer_id=1056" accept-charset="UTF-8" method="post">
       +
       +          <div class='form-group'>
       +            <label for='supervisor_volunteer_supervisor_id'>Select a Supervisor</label>
       +            <select name='supervisor_volunteer[supervisor_id]' class='form-control select2'>
       +                <option value="1053">Nicolas O&#39;Kon</option>
       +                <option value="1054">Mrs. Georgene Pagac</option>
       +                <option value="1055">Lonnie Kris</option>
       +            </select>
       +          </div>
       +          <input value="1056" autocomplete="off" type="hidden" name="supervisor_volunteer[volunteer_id]" id="supervisor_volunteer_volunteer_id" />
       +          <input type="submit" name="commit" value="Assign Supervisor" class="btn btn-primary" data-disable-with="Assign Supervisor" />
       +</form>    </div>
       +  </div>
       +</div>
       +
       +    </div>
       +  </div>
       +  <footer class="logged-in">
       +  <span class="copyright pull-left">© CASA / Volunteer Tracking</span>
       +  <span class="default-footer pull-right">
       +    <span class="col-12 col-sm-2">
       +      Built by <a href="https://rubyforgood.org/">Ruby For Good</a>
       +    </span>
       +    <span class="col-12 col-sm-2">
       +      <a href="https://form.typeform.com/to/iXY4BubB">Report a site issue</a>
       +    </span>
       +    <span class="col-12 col-sm-2">
       +      <a href="/sms-terms-conditions.html">SMS Terms &amp; Conditions</a>
       +    </span>
       +  </span>
       +</footer>
       +
       +</div>
       +</body>
       +</html>
     # ./spec/requests/volunteers_spec.rb:110:in `block (4 levels) in <top (required)>'
     # ./spec/requests/volunteers_spec.rb:110:in `each'
     # ./spec/requests/volunteers_spec.rb:110:in `block (3 levels) in <top (required)>'
     # /usr/local/bundle/gems/webmock-3.18.1/lib/webmock/rspec.rb:37:in `block (2 levels) in <top (required)>'

Finished in 4 minutes 36.6 seconds (files took 8.94 seconds to load)
2353 examples, 1 failure, 13 pending

Failed examples:

rspec ./spec/requests/volunteers_spec.rb:106 # /volunteers GET /edit shows correct supervisor options

```
### Expected Behavior
The test does not fail for names with apostrophes

_Login Details:_  
[Link to QA site](https://casa-qa.herokuapp.com/)  
[Link to new theme site](https://casa-new-theme.herokuapp.com/languages/new)  

Login Emails: 
- volunteer1@example.com  view site as a volunteer
- supervisor1@example.com view site as a supervisor
- casa_admin1@example.com view site as an admin
- all_casa_admin1@example.com view site as an all casa admin
  - go to `/all_casa_admins/sign_in`  

password for all users: 12345678  

### Questions? Join Slack!

We highly recommend that you join us in slack https://rubyforgood.herokuapp.com/ #casa channel to ask questions quickly and hear about office hours (currently Tuesday 5-7pm Pacific), stakeholder news, and upcoming new issues.

### PR DESCRIPTION
**Pull request by ciaranc78**
### What github issue is this PR for, if any?
Resolves #4683

### What changed, and why?
The updated test was breaking when a supervisor name included an apostrophe as `request.parse_body` was returning an escaped string (Nicolas O'Kon -> Nicolas O&#39;Kon).
Updated the test to compare with escaped string.

### How will this affect user permissions?
- Volunteer permissions: na
- Supervisor permissions: na
- Admin permissions: na

### How is this tested? (please write tests!) 💖💪
na

### Feelings gif (optional)
What gif best describes your feeling working on this issue? https://giphy.com/
How to embed:
`alt text`

### Feedback please? (optional)
We are very interested in your feedback! Please give us some :) https://forms.gle/1D5ACNgTs2u9gSdh9

### CODE REVIEW

File: spec/requests/volunteers_spec.rb [hunk 1]
```diff
@@ -106,8 +106,8 @@
     it "shows correct supervisor options", :aggregate_failures do
       supervisors = create_list(:supervisor, 3, casa_org: organization)
 
-      page = request.parsed_body
-      supervisors.each { |supervisor| expect(page).to include(supervisor.display_name.html_safe) }
+      page = CGI.unescapeHTML(request.parsed_body)
+      supervisors.each { |supervisor| expect(page).to include(supervisor.display_name) }
```
Comment (FireLemons) [inline spec/requests/volunteers_spec.rb:110]: It's not realistic to test the contents of the page as though it were not html escaped. Could you change the test to expect the HTML escaped text in the unchanged page? It also takes more effort to convert the whole page into an unescaped form

**Review by FireLemons — CHANGES_REQUESTED** [review]

File: spec/requests/volunteers_spec.rb (hunk 1 above)
Comment (ciaranc78) [reply spec/requests/volunteers_spec.rb]: thanks, that makes sense!

**Comment by FireLemons** [comment]
:medal_sports:
