### PR TITLE
fix: case court report modal ui changes

### LINKED ISSUE #5888: improve report generation modal from sidebar
## What type(s) of user does this feature affect?
 - supervisors
 - admins
 - volunteers

## Description

We have the following modal on the `/case_court_reports` to generate court report documents.

Image

You probably missed it but to generate a report you need to select a case. Aka fill in the dropdown highlighted below.

Image

Yea... Not great UX. 

Lets improve that. 

### Criteria for Completion

- [ ] Add a border to the dropdown input to make it more visible
- [ ] Use some Javascript to make the select required

## How to access the QA site
_Login Details:_  
[Link to QA site](https://casa-qa.herokuapp.com/)  

Login Emails: 
- volunteer1@example.com  view site as a volunteer
- supervisor1@example.com view site as a supervisor
- casa_admin1@example.com view site as an admin
- all_casa_admin1@example.com view site as an all casa admin
  - go to `/all_casa_admins/sign_in`  

password for all users: 12345678  

### Questions? Join Slack!

We highly recommend that you join us in [slack](https://join.slack.com/t/rubyforgood/shared_invite/zt-21pyz2ab8-H6JgQfGGI0Ab6MfNOZRIQA) #casa channel to ask questions quickly. And [discord](https://discord.gg/qJcw2RZH8Q) for office hours (currently Tuesday 5-7pm Pacific), stakeholder news, and upcoming new issues.

### PR DESCRIPTION
**Pull request by alex-yi37**
### What github issue is this PR for, if any?
Resolves #5888, #6165 

### What changed, and _why_?
This PR changes the modal displayed at `/case_court_reports` by constraining the width of the select options seen when the modal is opened. Currently, if an option is long enough it will overflow through the side of the modal, after these changes it is truncated with ellipses. It also now displays an error message when a user tries to generate a report without first making a selection and clears the error when a selection is made or the modal is closed. Closing the modal will also reset the selected case.

### How is this **tested**? (please write tests!) 💖💪
_Note: if you see a flake in your test build in github actions, please post in slack #casa "Flaky test: <link to failed build>" :) 💪_
_Note: We love [capybara](https://rubydoc.info/github/teamcapybara/capybara) tests! If you are writing both haml/js and ruby, please try to test your work with tests at every level including system tests like https://github.com/rubyforgood/casa/tree/main/spec/system_ 

### Screenshots please :)
_Run your local server and take a screenshot of your work! Try to include the URL of the page as well as the contents of the page._ 

#### Before: signed in as admin, selecting a long case option - there is no border around the option and it overflows when too long
image

#### Before: signed in as admin, trying to generate a report with no case selected. Does not tell user that selection is required, and keeps selection when modal is closed
https://github.com/user-attachments/assets/e9230f1e-49a9-4e9a-a94b-c70a84c0204f

#### After: signed in as admin, selecting a long case option - there's a border around the select element and it gets truncated with ellipses
image

#### After: signed in as admin, trying to generate report with case selected displays an error message. Making a selection clears the error. Closing the modal clears the error and also resets the selection
https://github.com/user-attachments/assets/9c58d250-9d01-4b84-85d9-ac8cfadfeefe

#### After: signed in as volunteer, select border styles are consistent with admin styles and error message still appears when trying to generate report without selecting an option
image

### Feelings gif (optional)
_What gif best describes your feeling working on this issue? https://giphy.com/
How to embed:_
`alt text`

### CODE REVIEW

File: app/javascript/src/casa_case.js [hunk 1]
```diff
@@ -127,20 +141,43 @@ function handleGenerateReport (e) {
...
+  $('#case-selection').on('change', clearSelectErrors)
+
   $('select.siblings-casa-cases').on('change', () => {
     if ($('select.siblings-casa-cases').find(':selected').text()) {
       enableBtn($('button.copy-court-button')[0])
     } else {
       disableBtn($('button.copy-court-button')[0])
     }
   })
+  // modal id is defined in _generate_docx.html.erb so would like to be able to implement modal close logic in that file
```
Comment (compwron) [inline app/javascript/src/casa_case.js:178]: good comment. I am not sure of the right solution here.

**Review by compwron — APPROVED** [review]
great test comments!
