### PR TITLE
5501 Bug in Case Contacts AfterParty task

### LINKED ISSUE #5501: Bug:Uncaught Exception in New After Party Task
## Impacted User Types
 - volunteers
 - supervisors
 - admins

## Description
Running the new [`set_case_contacts_as_active`](https://github.com/rubyforgood/casa/blob/main/lib/tasks/deployment/20231125151610_set_case_contacts_as_active.rake) after party task causes the attempted creation of invalid additional expenses.  

Stacktrace:
```
ActiveRecord::RecordInvalid: Validation failed: Additional expenses is invalid (ActiveRecord::RecordInvalid)
/app/vendor/bundle/ruby/3.2.0/gems/activerecord-7.0.8/lib/active_record/validations.rb:80:in `raise_validation_error'
/app/vendor/bundle/ruby/3.2.0/gems/activerecord-7.0.8/lib/active_record/validations.rb:53:in `save!'
/app/vendor/bundle/ruby/3.2.0/gems/activerecord-7.0.8/lib/active_record/transactions.rb:302:in `block in save!'
/app/vendor/bundle/ruby/3.2.0/gems/activerecord-7.0.8/lib/active_record/transactions.rb:354:in `block in with_transaction_returning_status'
/app/vendor/bundle/ruby/3.2.0/gems/activerecord-7.0.8/lib/active_record/connection_adapters/abstract/database_statements.rb:314:in `transaction'
/app/vendor/bundle/ruby/3.2.0/gems/activerecord-7.0.8/lib/active_record/transactions.rb:350:in `with_transaction_returning_status'
/app/vendor/bundle/ruby/3.2.0/gems/activerecord-7.0.8/lib/active_record/transactions.rb:302:in `save!'
/app/vendor/bundle/ruby/3.2.0/gems/activerecord-7.0.8/lib/active_record/suppressor.rb:54:in `save!'
/app/vendor/bundle/ruby/3.2.0/gems/scout_apm-5.3.5/lib/scout_apm/instruments/active_record.rb:428:in `save!'
/app/vendor/bundle/ruby/3.2.0/gems/activerecord-7.0.8/lib/active_record/persistence.rb:782:in `block in update!'
/app/vendor/bundle/ruby/3.2.0/gems/activerecord-7.0.8/lib/active_record/transactions.rb:354:in `block in with_transaction_returning_status'
/app/vendor/bundle/ruby/3.2.0/gems/activerecord-7.0.8/lib/active_record/connection_adapters/abstract/transaction.rb:319:in `block in within_new_transaction'
/app/vendor/bundle/ruby/3.2.0/gems/activesupport-7.0.8/lib/active_support/concurrency/load_interlock_aware_monitor.rb:25:in `handle_interrupt'
/app/vendor/bundle/ruby/3.2.0/gems/activesupport-7.0.8/lib/active_support/concurrency/load_interlock_aware_monitor.rb:25:in `block in synchronize'
/app/vendor/bundle/ruby/3.2.0/gems/activesupport-7.0.8/lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in `handle_interrupt'
/app/vendor/bundle/ruby/3.2.0/gems/activesupport-7.0.8/lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in `synchronize'
/app/vendor/bundle/ruby/3.2.0/gems/activerecord-7.0.8/lib/active_record/connection_adapters/abstract/transaction.rb:317:in `within_new_transaction'
/app/vendor/bundle/ruby/3.2.0/gems/activerecord-7.0.8/lib/active_record/connection_adapters/abstract/database_statements.rb:316:in `transaction'
/app/vendor/bundle/ruby/3.2.0/gems/activerecord-7.0.8/lib/active_record/transactions.rb:350:in `with_transaction_returning_status'
/app/vendor/bundle/ruby/3.2.0/gems/activerecord-7.0.8/lib/active_record/persistence.rb:780:in `update!'
/app/lib/tasks/deployment/20231125151610_set_case_contacts_as_active.rake:7:in `block (3 levels) in <top (required)>'
/app/vendor/bundle/ruby/3.2.0/gems/activerecord-7.0.8/lib/active_record/relation/delegation.rb:88:in `each'
/app/vendor/bundle/ruby/3.2.0/gems/activerecord-7.0.8/lib/active_record/relation/delegation.rb:88:in `each'
/app/lib/tasks/deployment/20231125151610_set_case_contacts_as_active.rake:6:in `block (2 levels) in <top (required)>'
/app/vendor/bundle/ruby/3.2.0/gems/bugsnag-6.26.1/lib/bugsnag/integrations/rake.rb:20:in `execute'
/app/vendor/bundle/ruby/3.2.0/gems/after_party-1.11.2/lib/tasks/deploy_task_runner.rake:6:in `block (3 levels) in <top (required)>'
/app/vendor/bundle/ruby/3.2.0/gems/after_party-1.11.2/lib/tasks/deploy_task_runner.rake:6:in `each'
/app/vendor/bundle/ruby/3.2.0/gems/after_party-1.11.2/lib/tasks/deploy_task_runner.rake:6:in `block (2 levels) in <top (required)>'
/app/vendor/bundle/ruby/3.2.0/gems/bugsnag-6.26.1/lib/bugsnag/integrations/rake.rb:20:in `execute'
/app/vendor/bundle/ruby/3.2.0/gems/rake-13.1.0/exe/rake:27:in `<top (required)>'
/app/bin/bundle:133:in `load'
/app/bin/bundle:133:in `<main>'
Tasks: TOP => after_party:set_case_contacts_as_active
```

Make the task handle the unexpected expenses

Login Emails: 
- volunteer1@example.com  view site as a volunteer
- supervisor1@example.com view site as a supervisor
- casa_admin1@example.com view site as an admin
- all_casa_admin1@example.com view site as an all casa admin
  - go to `/all_casa_admins/sign_in`  

password for all users: 12345678  

### Questions? Join Slack!

We highly recommend that you join us in [slack](https://join.slack.com/t/rubyforgood/shared_invite/zt-21pyz2ab8-H6JgQfGGI0Ab6MfNOZRIQA) #casa channel to ask questions quickly. And [discord](https://discord.gg/qJcw2RZH8Q) for office hours (currently Tuesday 5-7pm Pacific), stakeholder news, and upcoming new issues.

### PR DESCRIPTION
**Pull request by schoork**
### What github issue is this PR for, if any?
Resolves #5501 

### What changed, and why?
There are some additional expenses in the database that would no longer be considered valid. The update of the older Case Contacts is causing the validation on these to fail. This is reproducible given the following steps:

1. Reseed your database: `rails db:seed:replant`
2. In `app/models/additional_expense.rb` comment out the validation line
3. Make a new soon-to-be-invalid Additional Expense in the console: `CaseContact.first.additional_expenses.create!`
4. Set the specified CaseContact as a draft: `CaseContact.first.update(status: "started")`
5. Uncomment the validation line from step 2
6. Comment out the fix in this pull request from `lib/tasks/deployment/20231125151610_set_case_contacts_as_active.rake` (lines 7-9)
7. Run AfterParty: `bundle exec rake after_party:run`. It should fail.
8. Uncomment the fix in step 6
9. Run AfterParty: `bundle exec rake after_party:run`. It should pass.

### How will this affect user permissions?
- Volunteer permissions:
- Supervisor permissions:
- Admin permissions:

### Feelings gif (optional)
What gif best describes your feeling working on this issue? https://giphy.com/
How to embed:
`alt text`

### Feedback please? (optional)
We are very interested in your feedback! Please give us some :) https://forms.gle/1D5ACNgTs2u9gSdh9

### CODE REVIEW

File: lib/tasks/data_post_processors/case_contact_populator.rb [hunk 1]
```diff
@@ -1,6 +1,10 @@
 module CaseContactPopulator
   def self.populate
     CaseContact.find_each do |case_contact|
+      # Get rid of drafts
+      unless case_contact.casa_case
+        case_contact.destroy
+      end
```
Comment (schoork) [inline lib/tasks/data_post_processors/case_contact_populator.rb:7]: Not part of the fix, but you have drafts, then running `bin/update` fails without these lines.

File: lib/tasks/deployment/20231125151610_set_case_contacts_as_active.rake [hunk 2]
```diff
@@ -4,6 +4,10 @@ namespace :after_party do
     puts "Running deploy task 'set_case_contacts_as_active'"
 
     CaseContact.all.each do |cc|
+      cc.additional_expenses.each do |additional_expense|
+        additional_expense.update(other_expenses_describe: "No description given") unless additional_expense.other_expenses_describe
```
Comment (schoork) [inline lib/tasks/deployment/20231125151610_set_case_contacts_as_active.rake:8]: Could update this to be anything, but a blank string won't cut it.

File: lib/tasks/deployment/20231125151610_set_case_contacts_as_active.rake [hunk 3]
```diff
@@ -3,7 +3,11 @@ namespace :after_party do
   task set_case_contacts_as_active: :environment do
     puts "Running deploy task 'set_case_contacts_as_active'"
 
-    CaseContact.all.each do |cc|
+    CaseContact.where.not(casa_case_id: nil).each do |cc|
```
Comment (schoork) [inline lib/tasks/deployment/20231125151610_set_case_contacts_as_active.rake:6]: In case users can already create legit drafts in prod. This would stop it for failing for drafts that would fail other validations.

**Review by littleforest — APPROVED** [review]
