### PR TITLE
Fix email previews

### LINKED ISSUE #2809: Show error if user is of wrong type or nonexistant in email preview
**Description**
Some email previews can take a get parameter `id` to specify which user to show the email preview for. 
If the user is the wrong type of user for the preview or nonexistant, show an error instead of redirecting to a valid user.

**Screenshots of current behavior, if any**  
User with id=2265 is a volunteer  
image
If I try to pass this id to the account setup supervisor email preview, it shows the first supervisor   
image
Also if the email preview is passed a nonexistant user id the first supervisor is shown
image
Supervisor email preview working normally  
user with id=2185 is supervisor3@example.com
image

_QA Details:_  
[Link to QA site](https://casa-qa.herokuapp.com/)  
[QA Mailer previews](https://casa-qa.herokuapp.com/rails/mailers/)

casa_admin1@example.com view other users on the site as an admin
password: 123456  

### Questions? Join Slack!

We highly recommend that you join us in slack https://rubyforgood.herokuapp.com/ #casa channel to ask questions quickly and hear about office hours (currently Wednesday 6-8pm Pacific), stakeholder news, and upcoming new issues.

### PR DESCRIPTION
**Pull request by geeksilva97**
### What github issue is this PR for, if any?
Resolves #2809

### What changed, and why?
Prevent loading a record with a different id than given in the query params.

### How will this affect user permissions?
- Volunteer permissions: No changes
- Supervisor permissions: No changes
- Admin permissions: No changes

### Feedback please? (optional)
We are very interested in your feedback! Please give us some :) https://forms.gle/1D5ACNgTs2u9gSdh9

### CODE REVIEW

**Comment by geeksilva97** [comment]
Hi, @compwron. I noticed that the same could happen with the other mailer previews then I changed all previews.

**Review by compwron — APPROVED** [review]

**Comment by compwron** [comment]
Please take a look at the failing test and lint

File: lib/mailers/previews/casa_admin_mailer_preview.rb [hunk 1]
```diff
@@ -1,11 +1,11 @@
 class CasaAdminMailerPreview < ActionMailer::Preview
   def account_setup
-    casa_admin = CasaAdmin.find_by(id: params[:id]) || CasaAdmin.last
+    casa_admin = params.has_key?(:id) ? CasaAdmin.find_by(id: params[:id]) : CasaAdmin.last
```
Comment (wenderjean) [inline lib/mailers/previews/casa_admin_mailer_preview.rb:3]: It's weird because in practice it seems to me you'll end with the same behavior from the previous implementation. Considering the ticket itself asks for an error if the user is absent. :thinking:

Comment (geeksilva97) [reply lib/mailers/previews/casa_admin_mailer_preview.rb:3]: I understand from the PROBLEM that we need to show the error only if `id` is given and the user is not found. If the `id` is not provided, keep the behavior.

Comment (geeksilva97) [reply lib/mailers/previews/casa_admin_mailer_preview.rb:3]: What do you think about this @compwron?

Comment (compwron) [reply lib/mailers/previews/casa_admin_mailer_preview.rb:3]: > show the error only if id is given and the user is not found. If the id is not provided, keep the behavior.

This is correct

Comment (geeksilva97) [reply lib/mailers/previews/casa_admin_mailer_preview.rb:3]: Ok
