### PR TITLE
fix: scope ContactTypeGroup lookup to current organization to prevent cross-org access

### LINKED ISSUE #6351: Bug: Admins can edit Contact Type Groups across Organizations
## Impacted User Types
 - admins

## Expected Behavior
A warning showing "Sorry, you are not authorized to perform that action." is shown before an admin can edit a contact type group across an organization.

## How to Replicate
ex: 
1. - Log in as an admin.
2. - Click on "Edit Organization" in the left sidebar.
3. - Scroll down to under the header "Manage Contact Types".
4. - Click "Edit" on one of the contact types.
5. - Copy the link to the page.
6. - Log out.
7. - Log in as an admin from a different org `casa_admin2-1@example.com`
8. - Paste the link and visit it.
9. - Edit the name of the Contact Type Group.
10. - Log in as the original admin again.
11. - Navigate to the Contact Types again under "Edit Organization"
12. - See that the edit from the admin from the other org affected the Contact Type Group from this organization.

_Login Details:_  

Login Emails: 
- volunteer1@example.com  view site as a volunteer
- supervisor1@example.com view site as a supervisor
- casa_admin1@example.com view site as an admin
- all_casa_admin1@example.com view site as an all casa admin
  - go to `/all_casa_admins/sign_in`  

password for all users: 12345678  

### Questions? Join Slack!

We highly recommend that you join us in [slack](https://join.slack.com/t/rubyforgood/shared_invite/zt-21pyz2ab8-H6JgQfGGI0Ab6MfNOZRIQA) #casa channel to ask questions quickly. And [discord](https://discord.gg/qJcw2RZH8Q) for office hours (currently Tuesday 5-7pm Pacific), stakeholder news, and upcoming new issues.

### PR DESCRIPTION
**Pull request by PhutiCee**
## Summary
Fixes #6351

## Problem
An admin from Organization A could visit a direct URL containing the ID
of a ContactTypeGroup belonging to Organization B and successfully edit
or update it. This is a multi-tenancy data isolation bug.

## Root Cause
`set_contact_type_group` used `ContactTypeGroup.find(params[:id])`
which searches all records globally, ignoring the current user's org.

## Fix
Scoped the lookup to the current organization:

```ruby
# Before
@contact_type_group = ContactTypeGroup.find(params[:id])

# After
@contact_type_group = current_organization.contact_type_groups.find(params[:id])
```

Also added `rescue_from ActiveRecord::RecordNotFound` in
ApplicationController to return a proper 404 response instead of
raising an unhandled exception.

## Testing
- Added cross-org request spec for GET edit (expect 404)
- Added cross-org request spec for PUT update (expect 404, data unchanged)
- All 14 examples pass, 0 failures

## Notes
As @FireLemons noted, similar patterns may exist in HearingTypes and
Judge controllers and would be worth a follow-up fix.

### CODE REVIEW

File: app/controllers/contact_type_groups_controller.rb [hunk 1]
```diff
@@ -33,11 +35,18 @@ def update
 
   private
 
+  def record_not_found
```
Comment (compwron) [inline app/controllers/contact_type_groups_controller.rb:38]: In a future PR I want to move this handling to the top level controller that everything inherits from

File: Dockerfile [hunk 2]
```diff
@@ -5,46 +5,46 @@ ARG ROOT=/usr/src/app/
 FROM node:24-alpine AS node-source
 
 FROM ruby:4.0.2-alpine AS build
-  ARG ROOT
```
Comment (compwron) [inline Dockerfile:8]: This PR does not need a diff in the Dockerfile, please remove it

**Review by compwron — APPROVED** [review]
