### PR TITLE
Write a tests for dev and staging seed files

### LINKED ISSUE #790: write a test for dev and staging seed files to make sure they're not broken
see slack thread https://rubyforgood.slack.com/archives/CVB0QJGVD/p1600305358004800

### PR DESCRIPTION
**Pull request by Garbar**
Also, fix staging seed.rb with a typo
and fix miles_driven nil to 0 value

### What github issue is this PR for, if any?
Resolves #790 

### How will this affect user permissions?
- Volunteer permissions:
- Supervisor permissions:
- Admin permissions:

### Feelings gif (optional)
What gif best describes your feeling working on this issue? https://giphy.com/
How to embed:
`alt text`

### CODE REVIEW

File: db/seeds/staging.rb [hunk 1]
```diff
@@ -83,7 +83,7 @@ def case_number_generator
 CASA_CASE_COUNT.times do |index|
   new_casa_case = CasaCase.where(case_number: "CINA-#{yy}-#{1001 + index}").first_or_create!(
     casa_org_id: pg_casa.id,
-    transition_aged_youth: fakse
+    transition_aged_youth: false
```
Comment (jmkoni) [inline db/seeds/staging.rb:86]: Good catch 😅

**Review by jmkoni — APPROVED** [review]
Awesome!
