### PR TITLE
Fix N+1 issues in form_controller#show

### LINKED ISSUE #5893: fix CaseContacts::FormController#show N+1 issues
## What type(s) of user does this feature affect?
 - supervisors
 - admins
 - volunteers

## Description

This controller action has issues with N+1 queries (method call makes an additional method call for each item it finds.) 

You can see these in our scout: https://scoutapm.com/shares/305d1907-5748-420b-90cd-70594e0c9f25

Go through all the methods to ensure all the needed data is preloaded in the first query and no additional calls to the database need to be made.

## N+1 Resources

- sample PR https://github.com/rubyforgood/casa/pull/5868
- https://guides.rubyonrails.org/active_record_querying.html#eager-loading-associations
- https://medium.com/doctolib/how-to-find-fix-and-prevent-n-1-queries-on-rails-6b30d9cfbbaf
- https://github.com/flyerhzm/bullet?tab=readme-ov-file#log

## How to access the QA site
_Login Details:_  
[Link to QA site](https://casa-qa.herokuapp.com/)  

Login Emails: 
- volunteer1@example.com  view site as a volunteer
- supervisor1@example.com view site as a supervisor
- casa_admin1@example.com view site as an admin
- all_casa_admin1@example.com view site as an all casa admin
  - go to `/all_casa_admins/sign_in`  

password for all users: 12345678  

### Questions? Join Slack!

We highly recommend that you join us in [slack](https://join.slack.com/t/rubyforgood/shared_invite/zt-21pyz2ab8-H6JgQfGGI0Ab6MfNOZRIQA) #casa channel to ask questions quickly. And [discord](https://discord.gg/qJcw2RZH8Q) for office hours (currently Tuesday 5-7pm Pacific), stakeholder news, and upcoming new issues.

### PR DESCRIPTION
**Pull request by guswhitten**
### What github issue is this PR for, if any?
Resolves #5893

### What changed, and _why_?
Fixes the N+1 issues for the FormController#show that "bullet" complained about. Does this by preloading any record associations that are used later on.

### Screenshots please :)
Before:
casa-5893-before

After:
casa-5893-after

### CODE REVIEW

File: app/controllers/case_contacts/form_controller.rb [hunk 1]
```diff
@@ -49,18 +49,21 @@ def update
   private
 
   def set_case_contact
-    @case_contact = CaseContact.find(params[:case_contact_id])
```
Comment (compwron) [inline app/controllers/case_contacts/form_controller.rb:52]: (not this PR) someday we should add some `palicy_scope` to this 😓

**Review by compwron — APPROVED** [review]
nice!

**Comment by compwron** [comment]
We could add more tests for number of db queries using a library someday, but we don't have it yet
