### PR TITLE
Fix error message for bad court date for casa cases

### LINKED ISSUE #954: [bug] when incomplete court date is added and saved, error should show instead of "successfully updated" message
https://casa-qa.herokuapp.com/casa_cases/152/edit

Screen Shot 2020-10-04 at 2 55 52 PM
Screen Shot 2020-10-04 at 2 54 24 PM
Screen Shot 2020-10-04 at 2 56 22 PM
Screen Shot 2020-10-04 at 2 56 18 PM

### PR DESCRIPTION
**Pull request by jmkoni**
### What github issue is this PR for, if any?
Resolves #954 

### What changed, and why?
- Add capybara-screenshot gem to help debug capybara specs
- Add error message for incorrectly added court date for casa cases
- Checks for both an invalid date and a partial date

### How is this tested? (please write tests!) 💖💪
Added two additional tests for when a supervisor edits a casa case

### Screenshots please :)
Screen Shot 2020-10-05 at 10 27 55 AM

### CODE REVIEW

File: app/models/casa_case.rb [hunk 1]
```diff
@@ -54,11 +54,30 @@ def has_transitioned?
   end
 
   def update_cleaning_contact_types(args)
+    begin
```
Comment (jmkoni) [inline app/models/casa_case.rb:57]: I'm not a huge fan of this, but I couldn't think of a better way to do it without doing a begin/rescue in an even weirder place or trying to update first.

File: app/models/casa_case.rb [hunk 2]
```diff
@@ -54,11 +54,30 @@ def has_transitioned?
...
+  def parse_court_date(args)
+    day = args.delete("court_date(3i)")
+    month = args.delete("court_date(2i)")
+    year = args.delete("court_date(1i)")
+    return args if day.blank? && month.blank? && year.blank?
+    raise Date::Error if day.blank? || month.blank? || year.blank?
+    court_date = Date.parse("#{day}-#{month}-#{year}")
+    args["court_date"] = court_date
+    args
+  end
```
Comment (littleforest) [inline app/models/casa_case.rb:80]: Rails is smart enough to put the 3 separate pieces of the date together into the date field -- can we simplify this a bit by just returning an error if `court_date(1i)`, `court_date(2i)`, or `court_date(3i)` is blank?

**Review by littleforest — APPROVED** [review]
Looks good for now! Can simplify later if we put in a datepicker.
