### PR TITLE
Bug: Flaky Test Did not Receive Confirmation Text After Changing Admin to Supervisor

### LINKED ISSUE #5130: Bug: Flaky Test Did not Receive Confirmation Text After Changing Admin to Supervisor
Flaky tests are defined as tests that return both passes and failures despite no changes to the code or the test itself
Fix the test so it runs consistently.

### CI Workflow
rspec in docker

### Sample Error Output:
```
  1) casa_admins/edit can convert the admin to a supervisor
     Failure/Error: expect(page).to have_text("Admin was changed to Supervisor.")
       expected to find text "Admin was changed to Supervisor." in "Inbox\nSupervisors\nVolunteers\nOther Duties\nCases\nAdmins\nGroup Actions\nMenu\nUser 1960\nEdit Casa Admin\nEmail\nDisplay name\nPhone number\nEmail Reimbursement Requests\nCASA organization CASA Org 1618\nAdded to system August 15, 2023\nInvitation email sent never\nLast logged in never\nInvitation accepted never\nPassword reset last sent never\nWill receive reimbursement request emails No\nAdmin is\nACTIVE\nDeactivate Resend Invitation Change to Supervisor\nSubmit\n© CASA / Volunteer Tracking\nBuilt with by Ruby For Good\nReport a site issue\nSMS Terms & Conditions"

     [Screenshot Image]: /usr/src/app/tmp/capybara/failures_r_spec_example_groups_casa_admins_edit_can_convert_the_admin_to_a_supervisor_465.png


     # ./spec/system/casa_admins/edit_spec.rb:114:in `block (2 levels) in <top (required)>'
     # /usr/local/bundle/gems/webmock-3.18.1/lib/webmock/rspec.rb:37:in `block (2 levels) in <top (required)>'
```

### Questions? Join Slack!

We highly recommend that you join us in slack https://rubyforgood.herokuapp.com/ #casa channel to ask questions quickly and hear about office hours (currently Tuesday 5-7pm Pacific), stakeholder news, and upcoming new issues.

### PR DESCRIPTION
**Pull request by tonyaraujop**
### What github issue is this PR for, if any?
Resolves #5130 

### What changed, and why?

fix: flaky test by removing second user creation and changing the capybara finder to change supervisor.

### How will this affect user permissions?
- Volunteer permissions:
- Supervisor permissions:
- Admin permissions:

### Feelings gif (optional)
What gif best describes your feeling working on this issue? https://giphy.com/
How to embed:
`alt text`

### Feedback please? (optional)
We are very interested in your feedback! Please give us some :) https://forms.gle/1D5ACNgTs2u9gSdh9

### CODE REVIEW

File: spec/system/casa_admins/edit_spec.rb [hunk 1]
```diff
@@ -106,13 +106,14 @@
...
-    another = create(:casa_admin)
-    visit edit_casa_admin_path(another)
+    visit edit_casa_admin_path(admin)
 
-    click_on "Change to Supervisor"
+    page.find("a", text: "Change to Supervisor").click
 
-    expect(page).to have_text("Admin was changed to Supervisor.")
-    expect(User.find(another.id)).to be_supervisor
+    aggregate_failures do
```
Comment (chahmedejaz) [inline spec/system/casa_admins/edit_spec.rb:113]: I believe, this might not be a good approach to use this block in a production spec. It's better to use in local environment for testing.
We should not be running the user DB query at line#115, if the line#114's expectation gets failed.

Comment (tonyaraujop) [reply spec/system/casa_admins/edit_spec.rb:113]: Got it. I'll update the spec.

**Comment by FireLemons** [comment]
:medal_sports:
