### PR TITLE
Fix N+1 issues in casa_cases#show

### LINKED ISSUE #5892: fix CasaCasesController#show N+1 issues
## What type(s) of user does this feature affect?
 - supervisors
 - admins
 - volunteers

## Description

This controller action has issues with N+1 queries (method call makes an additional method call for each item it finds.) 

You can see these in our scout: https://scoutapm.com/shares/e7dee11b-72d2-4e94-b6b2-853908ded0a8

Go through all the methods to ensure all the needed data is preloaded in the first query and no additional calls to the database need to be made.

## N+1 Resources

- sample PR https://github.com/rubyforgood/casa/pull/5868
- https://guides.rubyonrails.org/active_record_querying.html#eager-loading-associations
- https://medium.com/doctolib/how-to-find-fix-and-prevent-n-1-queries-on-rails-6b30d9cfbbaf
- https://github.com/flyerhzm/bullet?tab=readme-ov-file#log

## How to access the QA site
_Login Details:_  
[Link to QA site](https://casa-qa.herokuapp.com/)  

Login Emails: 
- volunteer1@example.com  view site as a volunteer
- supervisor1@example.com view site as a supervisor
- casa_admin1@example.com view site as an admin
- all_casa_admin1@example.com view site as an all casa admin
  - go to `/all_casa_admins/sign_in`  

password for all users: 12345678  

### Questions? Join Slack!

We highly recommend that you join us in [slack](https://join.slack.com/t/rubyforgood/shared_invite/zt-21pyz2ab8-H6JgQfGGI0Ab6MfNOZRIQA) #casa channel to ask questions quickly. And [discord](https://discord.gg/qJcw2RZH8Q) for office hours (currently Tuesday 5-7pm Pacific), stakeholder news, and upcoming new issues.

### LINKED ISSUE #5893: fix CaseContacts::FormController#show N+1 issues
## What type(s) of user does this feature affect?
 - supervisors
 - admins
 - volunteers

## Description

This controller action has issues with N+1 queries (method call makes an additional method call for each item it finds.) 

You can see these in our scout: https://scoutapm.com/shares/305d1907-5748-420b-90cd-70594e0c9f25

Go through all the methods to ensure all the needed data is preloaded in the first query and no additional calls to the database need to be made.

## N+1 Resources

- sample PR https://github.com/rubyforgood/casa/pull/5868
- https://guides.rubyonrails.org/active_record_querying.html#eager-loading-associations
- https://medium.com/doctolib/how-to-find-fix-and-prevent-n-1-queries-on-rails-6b30d9cfbbaf
- https://github.com/flyerhzm/bullet?tab=readme-ov-file#log

## How to access the QA site
_Login Details:_  
[Link to QA site](https://casa-qa.herokuapp.com/)  

Login Emails: 
- volunteer1@example.com  view site as a volunteer
- supervisor1@example.com view site as a supervisor
- casa_admin1@example.com view site as an admin
- all_casa_admin1@example.com view site as an all casa admin
  - go to `/all_casa_admins/sign_in`  

password for all users: 12345678  

### Questions? Join Slack!

We highly recommend that you join us in [slack](https://join.slack.com/t/rubyforgood/shared_invite/zt-21pyz2ab8-H6JgQfGGI0Ab6MfNOZRIQA) #casa channel to ask questions quickly. And [discord](https://discord.gg/qJcw2RZH8Q) for office hours (currently Tuesday 5-7pm Pacific), stakeholder news, and upcoming new issues.

### PR DESCRIPTION
**Pull request by Kerman07**
### What github issue is this PR for, if any?
Resolves #5892

### What changed, and _why_?
Fixed the N+1 issues for the CasaCasesController#show that "bullet" complained about. Maybe the includes can be moved to the case_contacts_ordered_by_occurred_at method in the decorator since that is only used in the CaseContactsExportCsvService other than the uses here in the show.html and there the same entities are also preloaded.

### Screenshots please :)
Before:
Screenshot 2024-07-22 at 20 04 05

And after:
Screenshot 2024-07-22 at 20 02 42

### Feelings gif (optional)
_What gif best describes your feeling working on this issue? https://giphy.com/
How to embed:_
`alt text`

### CODE REVIEW

File: spec/models/case_contact_spec.rb [hunk 1]
```diff
@@ -551,13 +551,13 @@
...
-      contact_type2 = build_stubbed(:contact_type, contact_type_group: group2, name: "Medical Professional")
-      contact_type3 = build_stubbed(:contact_type, contact_type_group: group2, name: "Other Therapist")
+      group1 = create(:contact_type_group, name: "Family")
+      group2 = create(:contact_type_group, name: "Health")
+      contact_type1 = create(:contact_type, contact_type_group: group1, name: "Parent")
+      contact_type2 = create(:contact_type, contact_type_group: group2, name: "Medical Professional")
+      contact_type3 = create(:contact_type, contact_type_group: group2, name: "Other Therapist")
       case_contact_types = [contact_type1, contact_type2, contact_type3]
-      case_contact = build_stubbed(:case_contact)
+      case_contact = create(:case_contact)
```
Comment (ybocharov-aoi) [inline spec/models/case_contact_spec.rb:560]: These can be `build` instead of `create`. It would be a bit faster.

**Review by ybocharov-aoi — APPROVED** [review]
LGTM! This should help quite a bit. It one of our most used and slowest pages :slightly_smiling_face:

File: spec/models/case_contact_spec.rb (hunk 1 above)
Comment (elasticspoon) [reply spec/models/case_contact_spec.rb:560]: wrong account :man_facepalming:

**Review by elasticspoon — APPROVED** [review]
See comments from my other account.

File: spec/models/case_contact_spec.rb (hunk 1 above)
Comment (Kerman07) [reply spec/models/case_contact_spec.rb]: Had to keep the create for the case_contact, else the spec fails. Changed the other ones.
