### PR TITLE
Flaky test issue 5424

### LINKED ISSUE #5424: Bug: Flaky Test Case Contact Filter Mismatch
Flaky tests are defined as tests that return both passes and failures despite no changes to the code or the test itself
Fix the test so it runs consistently.

### CI Workflow
Rspec

### Sample Error Output:
```

  1) CaseContactReport filter behavior casa case number filter when providing casa case ids returns all case contacts with the casa case ids
     Failure/Error: expect(report.case_contacts).to eq(case_contacts)

       expected: [#<CaseContact id: 234, creator_id: 677, casa_case_id: 265, duration_minutes: 60, occurred_at: "2023-...: 0, want_driving_reimbursement: false, notes: nil, deleted_at: nil, reimbursement_complete: false>]
            got: #<ActiveRecord::Relation [#<CaseContact id: 236, creator_id: 679, casa_case_id: 265, duration_minutes... 0, want_driving_reimbursement: false, notes: nil, deleted_at: nil, reimbursement_complete: false>]>

       (compared using ==)

       Diff:
       @@ -1,4 +1,46 @@
       -[#<CaseContact id: 234, creator_id: 677, casa_case_id: 265, duration_minutes: 60, occurred_at: "2023-06-21 20:58:59.822510191 +0000", created_at: "2023-06-21 20:58:59.824615000 +0000", updated_at: "2023-06-21 20:58:59.824615000 +0000", contact_made: false, medium_type: "in-person", miles_driven: 0, want_driving_reimbursement: false, notes: nil, deleted_at: nil, reimbursement_complete: false>,
       - #<CaseContact id: 235, creator_id: 678, casa_case_id: 265, duration_minutes: 60, occurred_at: "2023-06-21 20:58:59.839691776 +0000", created_at: "2023-06-21 20:58:59.841769000 +0000", updated_at: "2023-06-21 20:58:59.841769000 +0000", contact_made: false, medium_type: "in-person", miles_driven: 0, want_driving_reimbursement: false, notes: nil, deleted_at: nil, reimbursement_complete: false>,
       - #<CaseContact id: 236, creator_id: 679, casa_case_id: 265, duration_minutes: 60, occurred_at: "2023-06-21 20:58:59.857011764 +0000", created_at: "2023-06-21 20:58:59.859142000 +0000", updated_at: "2023-06-21 20:58:59.859142000 +0000", contact_made: false, medium_type: "in-person", miles_driven: 0, want_driving_reimbursement: false, notes: nil, deleted_at: nil, reimbursement_complete: false>]
       +[#<CaseContact:0x00007f47cc01e9e0
       +  id: 236,
       +  creator_id: 679,
       +  casa_case_id: 265,
       +  duration_minutes: 60,
       +  occurred_at: Wed, 21 Jun 2023 20:58:59.857011000 UTC +00:00,
       +  created_at: Wed, 21 Jun 2023 20:58:59.859142000 UTC +00:00,
       +  updated_at: Wed, 21 Jun 2023 20:58:59.859142000 UTC +00:00,
       +  contact_made: false,
       +  medium_type: "in-person",
       +  miles_driven: 0,
       +  want_driving_reimbursement: false,
       +  notes: nil,
       +  deleted_at: nil,
       +  reimbursement_complete: false>,
       + #<CaseContact:0x00007f47cc01e8a0
       +  id: 234,
       +  creator_id: 677,
       +  casa_case_id: 265,
       +  duration_minutes: 60,
       +  occurred_at: Wed, 21 Jun 2023 20:58:59.822510000 UTC +00:00,
       +  created_at: Wed, 21 Jun 2023 20:58:59.824615000 UTC +00:00,
       +  updated_at: Wed, 21 Jun 2023 20:58:59.824615000 UTC +00:00,
       +  contact_made: false,
       +  medium_type: "in-person",
       +  miles_driven: 0,
       +  want_driving_reimbursement: false,
       +  notes: nil,
       +  deleted_at: nil,
       +  reimbursement_complete: false>,
       + #<CaseContact:0x00007f47cc01e760
       +  id: 235,
       +  creator_id: 678,
       +  casa_case_id: 265,
       +  duration_minutes: 60,
       +  occurred_at: Wed, 21 Jun 2023 20:58:59.839691000 UTC +00:00,
       +  created_at: Wed, 21 Jun 2023 20:58:59.841769000 UTC +00:00,
       +  updated_at: Wed, 21 Jun 2023 20:58:59.841769000 UTC +00:00,
       +  contact_made: false,
       +  medium_type: "in-person",
       +  miles_driven: 0,
       +  want_driving_reimbursement: false,
       +  notes: nil,
       +  deleted_at: nil,
       +  reimbursement_complete: false>]
     # ./spec/models/case_contact_report_spec.rb:318:in `block (5 levels) in <top (required)>'
```

change this line at `spec/models/case_contact_report_spec.rb:318`
```ruby
  expect(report.case_contacts).to eq(case_contacts)
```

to check that both lists of case contacts contain the same case contacts in any order.

The test fails because it erroneously checks that both lists have the same order.

### Questions? Join Slack!

We highly recommend that you join us in [slack](http://bit.ly/3Quxc1Q) #casa channel to ask questions quickly and hear about office hours (currently Tuesday 5-7pm Pacific), stakeholder news, and upcoming new issues.

### PR DESCRIPTION
**Pull request by hroulston**
### What github issue is this PR for, if any?
Resolves #5424 

### What changed, and why?
In case_contact_report.rb file I ordered the Case Contacts by id  under filtered_case_contacts method. Test passes since the order will match what is expected.

### How will this affect user permissions?
- Volunteer permissions: n/a
- Supervisor permissions: n/a
- Admin permissions: n/a

### How is this tested? (please write tests!) 💖💪
Test already in place, didn't need to change anything.

### Screenshots please :)
Screenshot 2023-12-12 at 1 34 13 PM

### Feelings gif (optional)
What gif best describes your feeling working on this issue? https://giphy.com/
How to embed:
`alt text`

### Feedback please? (optional)
We are very interested in your feedback! Please give us some :) https://forms.gle/1D5ACNgTs2u9gSdh9

### CODE REVIEW

File: app/models/case_contact_report.rb [hunk 1]
```diff
@@ -25,6 +25,7 @@ def filtered_case_contacts(args)
       .contact_type(args[:contact_type_ids])
       .contact_type_groups(args[:contact_type_group_ids])
       .with_casa_case(args[:casa_case_ids])
+      .order(:id)
```
Comment (FireLemons) [inline app/models/case_contact_report.rb:28]: Could you change the test instead of the app code?

**Review by FireLemons — CHANGES_REQUESTED** [review]

File: app/models/case_contact_report.rb (hunk 1 above)
Comment (hroulston) [reply app/models/case_contact_report.rb:28]: Sure no problem. Can I ask why it is preferable to go with Active Record's flaky ordering instead of explicit ordering? Happy to make the change, just pure curiosity.

Comment (FireLemons) [reply app/models/case_contact_report.rb]: Generally you don't wanna change the app code to make a test run. You want to just change the test.

Comment (hroulston) [reply app/models/case_contact_report.rb]: Ah got it, thank you :)

File: spec/models/case_contact_report_spec.rb [hunk 2]
```diff
@@ -315,7 +315,8 @@
         it "returns all case contacts with the casa case ids" do
           report = described_class.new({casa_case_ids: [casa_case.id]})
           expect(report.case_contacts.length).to eq(case_contacts.length)
-          expect(report.case_contacts).to eq(case_contacts)
+          expect(report.case_contacts).to include(*case_contacts)
```
Comment (hroulston) [inline spec/models/case_contact_report_spec.rb:318]: @FireLemons here are the two adjustments that work, do you have a preference of what is more appropriate?

Comment (compwron) [reply spec/models/case_contact_report_spec.rb:318]: Seems reasonable

Comment (compwron) [reply spec/models/case_contact_report_spec.rb:318]: there is also `match_array` which should match the contents of an array without worrying about the order
As long as the code stays working and the test stops flaking I think we're good

Comment (littleforest) [reply spec/models/case_contact_report_spec.rb:318]: I vote for `match_array`!

Comment (hroulston) [reply spec/models/case_contact_report_spec.rb]: @compwron @littleforest done! :)

**Review by schoork — APPROVED** [review]
I reverted the `Gemfile.lock` commit, since it didn't have to do with the test. 

I like this `match_array` matcher. I had to do some reading on that. Nice work @hroulston!

**Review by schoork — APPROVED** [review]
