### PR TITLE
[5894] Fix VolunteersController#edit N+1 issues

### LINKED ISSUE #5894: fix VolunteersController#edit N+1 issues
## What type(s) of user does this feature affect?
 - supervisors
 - admins
 - volunteers

## Description

This controller action has issues with N+1 queries (method call makes an additional method call for each item it finds.) 

You can see these in our scout: https://scoutapm.com/shares/5ebf4b86-2f24-46d1-94da-129efef60c43

Go through all the methods to ensure all the needed data is preloaded in the first query and no additional calls to the database need to be made.

## N+1 Resources

- sample PR https://github.com/rubyforgood/casa/pull/5868
- https://guides.rubyonrails.org/active_record_querying.html#eager-loading-associations
- https://medium.com/doctolib/how-to-find-fix-and-prevent-n-1-queries-on-rails-6b30d9cfbbaf
- https://github.com/flyerhzm/bullet?tab=readme-ov-file#log

## How to access the QA site
_Login Details:_  
[Link to QA site](https://casa-qa.herokuapp.com/)  

Login Emails: 
- volunteer1@example.com  view site as a volunteer
- supervisor1@example.com view site as a supervisor
- casa_admin1@example.com view site as an admin
- all_casa_admin1@example.com view site as an all casa admin
  - go to `/all_casa_admins/sign_in`  

password for all users: 12345678  

### Questions? Join Slack!

We highly recommend that you join us in [slack](https://join.slack.com/t/rubyforgood/shared_invite/zt-21pyz2ab8-H6JgQfGGI0Ab6MfNOZRIQA) #casa channel to ask questions quickly. And [discord](https://discord.gg/qJcw2RZH8Q) for office hours (currently Tuesday 5-7pm Pacific), stakeholder news, and upcoming new issues.

### PR DESCRIPTION
**Pull request by ElisaRmz**
### What github issue is this PR for, if any?
Resolves #5894

### What changed, and _why_?
When editing a Volunteer, an N+1 query occurred.
After the changes, it doesn't happen an the code is faster.

### How is this **tested**? (please write tests!) 💖💪
N+1 queries are tested with Bullet gem, a message is shown in the console

Add to your query

### Screenshots please :)
Previous queries
Antes
Actual queries
Captura de pantalla 2024-10-04 a las 16 15 12

### CODE REVIEW

File: app/helpers/ui_helper.rb [hunk 1]
```diff
@@ -5,14 +5,14 @@ def grouped_options_for_assigning_case(volunteer)
     [
       [
         "Not Assigned",
-        CasaCase
+        CasaCase.eager_load([:assigned_volunteers])
```
Comment (elasticspoon) [inline app/helpers/ui_helper.rb:8]: did you choose `eager_load` over `includes` on purpose? `includes` will choose to use `eager_load` or `preload`. It doesn't matter that much but just curious

**Review by elasticspoon — APPROVED** [review]
LGTM! Thank you!

File: app/helpers/ui_helper.rb (hunk 1 above)
Comment (ElisaRmz) [reply app/helpers/ui_helper.rb:8]: In this case, I followed the recommendation of Bullet gem. 
Firstly, include was suggested, but when added a new recommendation appeared with eager_load. (I didn't take a new screenshot)

**Comment by ElisaRmz** [comment]
@elasticspoon, I have a question: Can I merge it once it's approved, or is this only done by project owners?

**Comment by elasticspoon** [comment]
> @elasticspoon, I have a question: Can I merge it once it's approved, or is this only done by project owners?

Feel free to merge yourself. Or you can wait for me to do it.
