### PR TITLE
Bugfix/contact case report booleans

### LINKED ISSUE #1137: In Case Contact Report, Want Driving Reimbersement, Contact Made, Transition Aged Youth filters are not working
Sample params of a report request:

{
"start_date"=>"2020-05-19", 
"end_date"=>"2020-10-20", 
"supervisor_ids"=>["", "2"], 
"creator_ids"=>["", "1"], 
"contact_type_ids"=>["", "1", "2"], 
"contact_type_group_ids"=>["", "1", "2", "3", "4", "5", "6"], 
"want_driving_reimbursement"=>"true", 
"contact_made"=>"false", 
"has_transitioned"=>"", 
"commit"=>"Download Report"
}

Identified a bunch of other bugs relating to scopes of CaseContact used in CaseContactReport filters at:
 - /case_contact_reports

2. Want Driving Reimbersement, Contact Made, Transition Aged Youth filters **do not** work at all if selecting either Both / Yes / No. The params are of String type, then compare to a Boolean type. Example:

  ```rb
# app/models/case_contact.rb
  scope :contact_made, ->(contact_made = nil) {
    where(contact_made: contact_made) if contact_made == true || contact_made == false
  }
  scope :has_transitioned, ->(has_transitioned = nil) {
    joins(:casa_case).where(casa_cases: {transition_aged_youth: has_transitioned}) if has_transitioned == true || has_transitioned == false
  }
  scope :want_driving_reimbursement, ->(want_driving_reimbursement = nil) {
    where(want_driving_reimbursement: want_driving_reimbursement) if want_driving_reimbursement == true || want_driving_reimbursement == false
  }
```

The `where` blocks will never be includes.

I think we can rewrite them into:

```rb
where(contact_made: contact_made == "true") if contact_made&.length&.positive?

# `contact_made&.length&.positive?` will result to *false* 
# if `contact_made` is nil or empty.

```

OR, clean up the params in `case_contact_reports_controller` to pass in Boolean types TRUE / FALSE or nil if empty.

_Originally posted by @erik-trantt in https://github.com/rubyforgood/casa/issues/1117#issuecomment-712247123_

### PR DESCRIPTION
**Pull request by cassianoblonski**
### What github issue is this PR for, if any?
Resolves #1137 

### What changed, and why?
As suggested on the Issue, the radio buttons were designed to use boolean but they pass strings and this is the intended behavior radio buttons are not checkboxes so on the model scopes I fixed the comparison to strings.

### How is this tested? (please write tests!) 💖💪
Run the entire Rspec Test Suite and I made a spec to cover the scopes changes.

### CODE REVIEW

**Comment by cassianoblonski** [comment]
This PR depends on #1173 so we need to merge 1173 before this.

**Comment by cassianoblonski** [comment]
@jmkoni can you take a look at this PR now that #1173 is merged?

File: app/models/case_contact.rb [hunk 1]
```diff
@@ -33,13 +33,13 @@ class CaseContact < ApplicationRecord
     where("occurred_at BETWEEN ? AND ?", start_date, end_date) if start_date.present? && end_date.present?
   }
   scope :contact_made, ->(contact_made = nil) {
-    where(contact_made: contact_made) if contact_made == true || contact_made == false
+    where(contact_made: contact_made == "true") if contact_made == "true" || contact_made == "false"
```
Comment (jmkoni) [inline app/models/case_contact.rb:36]: Is there a reason to do this vs converting the string to a boolean earlier? This is making the code pretty confusing.

Comment (jmkoni) [reply app/models/case_contact.rb:36]: I found this: https://stackoverflow.com/questions/19339137/how-to-set-boolean-values-to-radio-buttons-in-rails-4-form

Comment (cassianoblonski) [reply app/models/case_contact.rb:36]: I agree with you, I tried changing the radio button to a boolean value but without success. I'm going to try again this way you linked, brb in a couple of minutes.

Comment (cassianoblonski) [reply app/models/case_contact.rb:36]: I tried this way and the params are still strings, after some research I think its the intended design of radio buttons to pass the value as strings.

the snippet I used:
```ruby
  <div class="field form-group">
    <label><strong>Transition Aged Youth:</strong></label>
    <div class="form-check">
      <%= f.radio_button(:has_transitioned, '', class: "form-check-input", checked: true, value: '') %>
      <%= f.label(:has_transitioned, 'Both', class: "form-check-label") %><br>

      <%= f.radio_button(:has_transitioned, true, class: "form-check-input", value: true) %>
      <%= f.label(:has_transitioned, 'Yes', class: "form-check-label") %><br>

      <%= f.radio_button :has_transitioned, false, value: false, class: "form-check-input" %>
      <%= f.label :has_transitioned, "No", value: false, class: "form-check-label" %><br>
    </div>
  </div>
```
params passed
image

Comment (jmkoni) [reply app/models/case_contact.rb:36]: Yeah I'm also in favor of just converting after the strong params. Also, is there a reason to have both? Either a youth has or hasn't transitioned...

**Review by compwron — APPROVED** [review]
Nice tests! :)
