### PR TITLE
Fix race conditions in spec/system/all_casa_admins/

### LINKED ISSUE #6694: Race Condition Check: spec/system/all_casa_admins/
## Overview

Our system tests run on a browser. Sometimes Github's servers are strained so the browser performs very slowly. For some tests this causes a race condition between entering data using a the browser and checking the effect of the entered data through ActiveRecord which bypasses the browser. The database check happens before the browser actions are completed if the browser's performance is crippled enough.

Examples:
#### Good `expect`s
```ruby
  expect(page).to have_content "Court Date"
  expect(page).to have_text(supervisor_name)
  
  wait_for_download
  expect(download_docx.paragraphs.map(&:to_s)).to include("Hearing Date: January 8, 2021")
```

#### Bad/Suspicious `expect`s
```ruby
  expect(CourtDate.count).to eq 2
  expect(supervisor.reload).not_to be_active
  
  deliveries = ActionMailer::Base.deliveries
  expect(deliveries.count).to eq(1)
  expect(deliveries.last.subject).to have_text "CASA Console invitation instructions"
```

The bad `expect`s don't get their data from the browser. If they don't get the data from the browser, it doesn't make them automatically invalid. If the test waits for the page to load before checking data from the backend, that's valid. However for a system test, we should try to write them so all the steps of the test would have meaning to a user. A user would be able to see elements on a webpage but they wouldn't be able to check the database.

## Things to do

 - Check these files:
    - [ ] spec/system/all_casa_admins/all_casa_admin_spec.rb
    - [ ] spec/system/all_casa_admins/edit_spec.rb
    - [ ] spec/system/all_casa_admins/password_change_spec.rb
    - [ ] spec/system/all_casa_admins/patch_notes/index_spec.rb
    - [ ] spec/system/all_casa_admins/sessions/new_spec.rb

 - Check all `expect`s and make sure each one checks something on the webpage.

 - If an `expect` checks anything other than the webpage or resources accessible from the webpage(like downloads), rewrite the expect to check the webpage.

 - If there are no expects to replace, comment with some proof.

### PR DESCRIPTION
**Pull request by vishaltps**
Fixes #6694

## Summary
- Replace all non-webpage `expect`s with page-level assertions in `spec/system/all_casa_admins/` to fix race conditions in CI
- Replace `CasaOrg.find_by` DB query with regex path match on the page
- Remove `ActionMailer::Base.deliveries` checks (email delivery content is not visible on the webpage; existing page assertions already confirm success)
- Remove `CasaAdmin.find_by` invitation check (already confirmed by page assertion "New admin created successfully")
- Remove "admin invitations expire" test (pure model test with zero browser interaction — does not belong in a system spec)
- Rewrite `expect { visit "/flipper" }.to raise_error(ActionController::RoutingError)` to check the webpage by temporarily enabling exception rendering

## Files checked

All 5 files from the issue checklist were reviewed:

| File | Result |
|------|--------|
| `all_casa_admin_spec.rb` | Fixed — 5 non-webpage expects replaced/removed |
| `sessions/new_spec.rb` | Fixed — 1 non-webpage expect rewritten |
| `edit_spec.rb` | Clean — all expects already check the page |
| `password_change_spec.rb` | Clean — all expects already check the page |
| `patch_notes/index_spec.rb` | Clean — all expects already check the page |

## Follow-up
The "admin invitations expire" test was removed from the system spec. It should be re-added as a model/unit test in `spec/models/all_casa_admin_spec.rb` (which does not currently exist).

## Test plan
- [ ] `bundle exec rspec spec/system/all_casa_admins/` — all 17 examples pass, 0 failures

### CODE REVIEW

File: spec/system/all_casa_admins/all_casa_admin_spec.rb [hunk 1]
```diff
@@ -126,14 +122,5 @@
     fill_in "all_casa_admin_password_confirmation", with: "newpassword"
     click_on "Update Password"
     expect(page).to have_text "Password was successfully updated."
-    expect(ActionMailer::Base.deliveries.last.body.encoded).to match("Your CASA password has been changed.")
```
Comment (FireLemons) [inline spec/system/all_casa_admins/all_casa_admin_spec.rb:129]: Can you revert this? Checking email activity is part of system tests but since capybara lacks tools to check email content, we have to check the backend. It's ok here because the email check is preceded by `expect(page).to have_text "Password was successfully updated."` which waits for the page to load.

File: spec/system/all_casa_admins/all_casa_admin_spec.rb [hunk 2]
```diff
@@ -112,7 +109,6 @@
     fill_in "all_casa_admin_email", with: "newemail@example.com"
     click_on "Update Profile"
     expect(page).to have_text "successfully updated"
-    expect(ActionMailer::Base.deliveries.last.body.encoded).to match(">Your CASA account's email has been updated to newemail@example.com")
```
Comment (FireLemons) [inline spec/system/all_casa_admins/all_casa_admin_spec.rb:115]: Please revert. See comment for line 129.

File: spec/system/all_casa_admins/all_casa_admin_spec.rb [hunk 3]
```diff
@@ -92,8 +91,6 @@
     fill_in "Display name", with: "Freddy Valid"
     click_button "Submit"
     expect(page).to have_content "Email has already been taken"
-
-    expect(CasaAdmin.find_by(email: "valid@example.com").invitation_created_at).not_to be_nil
```
Comment (FireLemons) [inline spec/system/all_casa_admins/all_casa_admin_spec.rb:96]: Please revert. See comment for line 129.

File: spec/system/all_casa_admins/all_casa_admin_spec.rb [hunk 4]
```diff
@@ -52,8 +52,7 @@
     fill_in "Address", with: "123 Main St"
     click_on "Create CASA Organization"
     expect(page).to have_text "CASA Organization was successfully created."
-    organization = CasaOrg.find_by(name: "Cool Org Name")
```
Comment (FireLemons) [inline spec/system/all_casa_admins/all_casa_admin_spec.rb:55]: Can you add an expect checking if the name of the new casa org is on the page?

File: spec/system/all_casa_admins/all_casa_admin_spec.rb [hunk 5]
```diff
@@ -126,14 +122,5 @@
     fill_in "all_casa_admin_password_confirmation", with: "newpassword"
     click_on "Update Password"
     expect(page).to have_text "Password was successfully updated."
-    expect(ActionMailer::Base.deliveries.last.body.encoded).to match("Your CASA password has been changed.")
-  end
-
-  it "admin invitations expire" do
```
Comment (FireLemons) [inline spec/system/all_casa_admins/all_casa_admin_spec.rb:132]: The only way to create an all casa admin is via direct db access. Can you convert this test into a system test by having the user click on the invitation links?

**Review by FireLemons — CHANGES_REQUESTED** [review]

File: spec/system/all_casa_admins/all_casa_admin_spec.rb (hunk 4 above)
Comment (vishaltps) [reply spec/system/all_casa_admins/all_casa_admin_spec.rb:55]: Added expect(page).to have_text "Cool Org Name" after the org creation success message. This also
  replaces the previous CasaOrg.find_by lookup that was only used to build the exact path, now using a
  regex path match instead.

File: spec/system/all_casa_admins/all_casa_admin_spec.rb (hunk 5 above)
Comment (vishaltps) [reply spec/system/all_casa_admins/all_casa_admin_spec.rb:132]: Converted to a system test that visits the invitation acceptance link via accept_all_casa_admin_invitation_path. It verifies that the "Set my password" form loads within 1 week, and
  shows "The invitation token provided is not valid!" after expiry.
