### PR TITLE
fix yarn lint error in case_contact.js

### LINKED ISSUE #721: Yarn lint fixes
lint errors in app/javascript/src/case_contact.js

### PR DESCRIPTION
**Pull request by abachman**
fixes #721

### CODE REVIEW

**Review by jmkoni — APPROVED** [review]

File: app/javascript/src/case_contact.js [hunk 1]
```diff
@@ -1,4 +1,4 @@
-/* global alert */
+/* global alert $ */
```
Comment (compwron) [inline app/javascript/src/case_contact.js:1]: What does this do?

**Review by compwron — APPROVED** [review]
