### PR TITLE
Banner Dismissed Forever Bug fix

### LINKED ISSUE #5428: Bug: Banner dismissed forever
## Impacted User Types
 - volunteers
 - supervisors
 - admins

## Environment
QA and Prod

## Current Behavior
When a user dismisses an "active" banner in one session, the banner never shows up for them again - it is dismissed forever

https://www.loom.com/share/9d0312d7095b4419bf760bcd0de22d0f

## Expected Behavior
active banners should show up for every session for a user as long as the banner is "active"

## How to Replicate
ex: 
1. Log in as an admin or supervisor.
2. Click on "Banners"
3. Create a new banner and set it to "active"
4. Dismiss the banner for yourself
5. End your session by logging out and log back in
6. Notice the banner is not showing for you despite it still being active

## How to access the QA site
_Login Details:_  
[Link to QA site](https://casa-qa.herokuapp.com/)  

Login Emails: 
- volunteer1@example.com  view site as a volunteer
- supervisor1@example.com view site as a supervisor
- casa_admin1@example.com view site as an admin
- all_casa_admin1@example.com view site as an all casa admin
  - go to `/all_casa_admins/sign_in`  

password for all users: 12345678  

### Questions? Join Slack!

We highly recommend that you join us in [slack](http://bit.ly/3Quxc1Q) #casa channel to ask questions quickly. And [discord](https://discord.gg/qJcw2RZH8Q) for office hours (currently Tuesday 5-7pm Pacific), stakeholder news, and upcoming new issues.

### PR DESCRIPTION
**Pull request by schoork**
### What github issue is this PR for, if any?
Resolves #5428 

This is an alternate PR to #5452. It makes use of session variables so they are cleared automatically when a user logs out.

### What changed, and why?

1. The original implementation made use of a cookie, which persists past user sessions. This switches to use session storage, which is destroyed when a user logs out.
2. A few minor code changes to clean up original code.

### How will this affect user permissions?
- Volunteer permissions:
- Supervisor permissions:
- Admin permissions:

### How is this tested? (please write tests!) 💖💪
- spec/system/banners/dismiss_spec.rb
- spec/requests/banners_spec.rb

### Screenshots please :)
Screenshot 2024-01-06 at 10 04 31 AM
Screenshot 2024-01-06 at 10 04 25 AM

### Feelings gif (optional)
What gif best describes your feeling working on this issue? https://giphy.com/
How to embed:
`alt text`

### Feedback please? (optional)
We are very interested in your feedback! Please give us some :) https://forms.gle/1D5ACNgTs2u9gSdh9

### CODE REVIEW

File: app/controllers/application_controller.rb [hunk 1]
```diff
@@ -30,6 +31,13 @@ def after_sign_out_path_for(resource_or_scope)
     end
   end
 
+  def set_active_banner
+    return nil unless current_organization
+
+    @active_banner = current_organization.banners.active.first
+    @active_banner = nil if session[:dismissed_banner] == @active_banner&.id
```
Comment (littleforest) [inline app/controllers/application_controller.rb:38]: Should this session variable actually hold an array of dismissed banners? Or does it not really matter since we can only have one active banner at a time.

Comment (schoork) [reply app/controllers/application_controller.rb:38]: There's only one active banner at once so I think it's 50-50 on whether to store an array of IDs or just the single one. Since storing an array in session storage is simple but non-trivial, I'd opt for the single ID until we need otherwise.

**Review by compwron — APPROVED** [review]
seems reasonable
yay tests :)
