### PR TITLE
Fix the case group multiselect.

### LINKED ISSUE #5136: Make Selecting Cases when Creating a Case Group More Accessible
## What type(s) of user does this feature affect?
 - admins

## Description
A case group can be made by
 1. logging in as an admin
 2. going to the cases tab
 3. clicking case groups top right of the table
 4. clicking new case group

Currently we have this to select cases when making a new case group
image

To select multiple cases using this a user has to hold either ctrl or shift.

We would like it to be like this to be more accessible
image
image

Write tests

See: https://github.com/rubyforgood/casa/wiki/Working-with-Frontend-Assets

## How to access the QA site
_Login Details:_  
[Link to QA site](https://casa-qa.herokuapp.com/)  

Login Emails: 
- volunteer1@example.com  view site as a volunteer
- supervisor1@example.com view site as a supervisor
- casa_admin1@example.com view site as an admin
- all_casa_admin1@example.com view site as an all casa admin
  - go to `/all_casa_admins/sign_in`  

password for all users: 12345678  

### Questions? Join Slack!

We highly recommend that you join us in slack https://rubyforgood.herokuapp.com/ #casa channel to ask questions quickly and hear about office hours (currently Tuesday 5-7pm Pacific), stakeholder news, and upcoming new issues.

### PR DESCRIPTION
**Pull request by seanmarcia**
### What github issue is this PR for, if any?
Resolves #5136 

### What changed, and why?

Makes the case group more accessible.

image

image

image

### CODE REVIEW

File: app/javascript/src/multiselect.js [hunk 1]
```diff
@@ -0,0 +1,231 @@
...
+  width: 1.15em;
+  margin-right: 0.35em;  
+}
+.multiselect-dropdown-list div.checked{
+}
+.multiselect-dropdown-list div:hover{
+  background-color: #ced4da;
+}
+.multiselect-dropdown span.maxselected {width:100%;}
+.multiselect-dropdown-all-selector {border-bottom:solid 1px #999;}
```
Comment (FireLemons) [inline app/javascript/src/multiselect.js:84]: Please move this to a sass file

File: public/assets/css/main.css [hunk 2]
```diff
@@ -1083,7 +1083,7 @@ h6,
     font-size: 14px;
     font-weight: 500;
     color: #262d3f;
-    display: block;
+    display: inline;
```
Comment (FireLemons) [inline public/assets/css/main.css:1086]: Isn't this the plainadmin theme's file? Maybe we want to override their rule with our own css instead of rewriting their theme

**Review by FireLemons — CHANGES_REQUESTED** [review]

**Comment by FireLemons** [comment]
Did you write this component or get it from somewhere? I'm wondering if we can just install it via yarn.

**Comment by seanmarcia** [comment]
It's from here: https://github.com/admirhodzic/multiselect-dropdown

I'll take a look on npm/yarn for an importable one.

**Comment by schoork** [comment]
I replaced the custom-built JS and CSS with [TomSelect](https://tom-select.js.org/). It integrates very easily/nicely with Bootstrap and Stimulus.

File: app/models/case_group.rb [hunk 3]
```diff
@@ -1,6 +1,6 @@
 class CaseGroup < ApplicationRecord
   belongs_to :casa_org
-  has_many :case_group_memberships
+  has_many :case_group_memberships, dependent: :destroy
```
Comment (schoork) [inline app/models/case_group.rb:3]: This fixes a foreign key constraint issue when clicking delete on the Case Groups page.

File: public/assets/css/main.css (hunk 2 above)
Comment (schoork) [reply public/assets/css/main.css]: Reverted

File: app/javascript/src/multiselect.js (hunk 1 above)
Comment (schoork) [reply app/javascript/src/multiselect.js]: Fixed

**Review by compwron — APPROVED** [review]
