### PR TITLE
Fix All CASA Admin "Change Password" button

### LINKED ISSUE #6527: Bug: "Change Password" button does not expand/collapse password form on All CASA Admin edit page (Bootstrap 5 collapse issue)
## Impacted User Types
 - all CASA admins

## Environment
- Local development
- QA site (https://casa-qa.herokuapp.com/)
- Desktop web
- Firefox

## Current Behavior
When I click the "Change Password" button on the All CASA Admin edit profile page, the password form does not appear (collapse does not work).

Image

## Expected Behavior
When I click "Change Password," the password form should expand/collapse using Bootstrap's collapse/accordion functionality.

Image

## How to Replicate
1. Log in as an all casa admin at /all_casa_admins/sign_in (use email: all_casa_admin1@example.com, password: 12345678).
2. Go to your profile edit page.
3. Click the "Change Password" button.
4. Observe that the password form does not appear.

## How to access the QA site
_Login Details:_  
[Link to QA site](https://casa-qa.herokuapp.com/)  

Login Emails: 
- volunteer1@example.com  view site as a volunteer
- supervisor1@example.com view site as a supervisor
- casa_admin1@example.com view site as an admin
- all_casa_admin1@example.com view site as an all casa admin
  - go to `/all_casa_admins/sign_in`  

password for all users: 12345678  

### Questions? Join Slack!

We highly recommend that you join us in [slack](https:https://join.slack.com/t/rubyforgood/shared_invite/zt-35218k86r-vlIiWqig54c9t~_LkGpQ7Q) #casa channel to ask questions quickly. And [discord](https://discord.gg/qJcw2RZH8Q) for office hours (currently Tuesday 5-7pm Pacific), stakeholder news, and upcoming new issues.

### PR DESCRIPTION
**Pull request by AudTheCodeWitch**
### What github issue is this PR for, if any?
Resolves #6527

### What changed, and _why_?
The bug fix updates the "Change Password" button and collapse form in `app/views/all_casa_admins/edit.html.erb` to use Bootstrap 5 attributes (`data-bs-toggle`, `data-bs-target`) instead of Bootstrap 4 (`data-toggle`, `data-target`). The parent accordion reference was also removed. Previously, clicking "Change Password" did not expand the password form due to outdated attributes, preventing admins from updating their password. Now, the button correctly toggles the password form, restoring expected functionality and improving user experience.

### How is this **tested**?
**New test files added:**
- `spec/views/all_casa_admins/edit.html.erb_spec.rb` — verifies the correct rendering and behavior of the edit profile view.
- `spec/system/all_casa_admins/edit_spec.rb` — covers system-level interactions for editing admin profiles.
- `spec/system/all_casa_admins/password_change_spec.rb` — tests the password change workflow, including form expansion and successful/failed updates.

**Manual testing:**
- Navigated to `/all_casa_admins/edit` locally, confirmed the password form expands and updates work. See Loom demo and screenshots below.

**Demo**
[dbb1b4d5e5f344b4972735dc693e5386-51f60ae5c0f4e762-full-play](https://www.loom.com/share/dbb1b4d5e5f344b4972735dc693e5386?sid=b73db727-ba6d-4050-86e2-eff011ba6bcb)

**Before:**
Screenshot 2025-10-06 at 2 58 57 PM

**After:**
Screenshot 2025-10-06 at 2 59 08 PM

### Feelings gif
Jim Halpert from The Office saying, "Problem solved."`

### CODE REVIEW

File: spec/system/all_casa_admins/edit_spec.rb [hunk 1]
```diff
@@ -0,0 +1,35 @@
+# frozen_string_literal: true
+
+require "rails_helper"
+
+RSpec.describe "AllCasaAdmin edit page", type: :system do
```
Comment (compwron) [inline spec/system/all_casa_admins/edit_spec.rb:5]: yay system spec!

**Review by compwron — APPROVED** [review]

**Comment by compwron** [comment]
un/fortunately, part of the point of having both the rspec and docker builds, is to 1. make sure docker keeps working but 2. to be able to tell when one of them is failing on a flake, i.e. *both* of them are not failing
