### PR TITLE
fix: fixes the list of "no_recent_sign_in" on supervisor weekly_digest

### LINKED ISSUE #4672: Email bug: Inactive volunteers list is inaccurate - tracks logged in at but login lasts several days, so do most recent of case contact created OR logged in at
Volunteers that have been active are still showing up

### PR DESCRIPTION
**Pull request by LeGorge**
### What github issue is this PR for, if any?
Resolves #4672 

### What changed, and why?
 - Changes the list of Volunteers the `weekly digest` supervisor email shows in the section `no_recent_sign_in`:
   - It was pointed out here https://github.com/rubyforgood/casa/issues/4672#issuecomment-1636244266 that the list should use the more recent of `last_sign_in_at` or last case_contact created. My understanding of it is that even if a volunteer has not logged in in the last 30 days, but he has a "recent" case_contact associated, the email section should not list that volunteer.
   - I used the case_contact's `occurred_at` field. Please verify and let me know that this is the field we want instead of using one of the other regular timestamps.
   - I changed the text in the email to let the supervisor know of that new behaviour.
   - I chose to maintain `User.no_recent_sign_in` as a scope even though this was the only place where it was used, so I just created a new call for supervisors to get that exact list. I feel like this situation should have its own name, but I'll leave that for you guys to figure out, in the meantime I used a big explanatory one just in case... let me know...

### How will this affect user permissions?
- No change

### How is this tested? (please write tests!) 💖💪
 - Added specs making sure all 3 scenarios are included and verified

### Screenshots please :)
 - does not apply

### CODE REVIEW

**Comment by schoork** [comment]
Great work @LeGorge! I added a few tests, changed the wording a little, and made two small logical changes. Will highlight in the diff.

File: app/models/supervisor.rb [hunk 1]
```diff
@@ -37,6 +37,14 @@ def pending_volunteers
     ).where(invitation_accepted_at: nil).where.not(invitation_created_at: nil)
   end
 
+  def inactive_volunteers
+    recent_case_contact_volunteer_ids = volunteers.joins(:case_contacts).where(
+      case_contacts: {created_at: 30.days.ago..}
```
Comment (schoork) [inline app/models/supervisor.rb:42]: Changed `occurred_at` to `updated_at`. Since these can be done in the past, a volunteer could create a contact 5 days in the past, and then the occurred_at might be misleading in the future.

File: app/models/user.rb [hunk 2]
```diff
@@ -56,7 +56,7 @@ class User < ApplicationRecord
     where(casa_org_id: org.id)
   }
 
-  scope :no_recent_sign_in, -> { active.where("last_sign_in_at <= ?", 30.days.ago) }
+  scope :no_recent_sign_in, -> { active.where("last_sign_in_at <= ?", 30.days.ago).or(User.active.where(last_sign_in_at: nil)) }
```
Comment (schoork) [inline app/models/user.rb:59]: Added the or clause for users who had never signed in. Found the use case when viewing in the mailer preview.

File: app/mailers/supervisor_mailer.rb [hunk 3]
```diff
@@ -10,6 +10,7 @@ def weekly_digest(supervisor)
     @supervisor = supervisor
     @casa_organization = supervisor.casa_org
     @inactive_messages = InactiveMessagesService.new(supervisor).inactive_messages
+    @inactive_volunteers = supervisor.inactive_volunteers
```
Comment (schoork) [inline app/mailers/supervisor_mailer.rb:13]: Moved the logic from the view to the mailer.

**Review by schoork — APPROVED** [review]
