### PR TITLE
display error when the chart faills to load

### LINKED ISSUE #4867: Display Error Message When metrics chart fails to load
**Description**
When the chart at `/health` fails to load. Show an error explaining why.
The chart at `/health` currently fails to load if viewed when not logged in and loads successfully when logged in.

See it in our QA environment: https://casa-qa.herokuapp.com/health
See: https://github.com/rubyforgood/casa/wiki/Working-with-Frontend-Assets
See: https://www.chartjs.org/

_Login Details:_  
[Link to QA site](https://casa-qa.herokuapp.com/)  

Login Emails: 
- volunteer1@example.com  view site as a volunteer
- supervisor1@example.com view site as a supervisor
- casa_admin1@example.com view site as an admin
- all_casa_admin1@example.com view site as an all casa admin
  - go to `/all_casa_admins/sign_in`  

password for all users: 12345678  

### Questions? Join Slack!

We highly recommend that you join us in slack https://rubyforgood.herokuapp.com/ #casa channel to ask questions quickly and hear about office hours (currently Tuesday 5-7pm Pacific), stakeholder news, and upcoming new issues.

### PR DESCRIPTION
**Pull request by Nwabor**
### What github issue is this PR for, if any?
Resolves #4867

### What changed, and why?
In app/assets/javascript/display_app_metric.js I added a callback function to handle errors whenever the chart didn't display

### How will this affect user permissions?
- Volunteer permissions: N/A
- Supervisor permissions: N/A
- Admin permissions: N/A

### Screenshots please :)
SampleTest

### Feelings gif (optional)
What gif best describes your feeling working on this issue? https://giphy.com/
How to embed:
`alt text`

### Feedback please? (optional)
We are very interested in your feedback! Please give us some :) https://forms.gle/1D5ACNgTs2u9gSdh9

### CODE REVIEW

File: app/javascript/application.js [hunk 1]
```diff
@@ -1,37 +1,37 @@
 /* global window */
 
-import './jQueryGlobalizer.js'
-import 'bootstrap'
-import 'bootstrap-select'
-import './sweet-alert-confirm.js'
+import "./jQueryGlobalizer.js";
+import "bootstrap";
+import "bootstrap-select";
+import "./sweet-alert-confirm.js";
```
Comment (FireLemons) [inline app/javascript/application.js:7]: Change all of the double quotes back. It's causing the [linter](https://www.testim.io/blog/what-is-a-linter-heres-a-definition-and-quick-start-guide/) to fail. Other things are causing the linter to fail too. Check the yarn lint check output for more details

File: app/javascript/src/display_app_metric.js [hunk 2]
```diff
@@ -1,120 +1,140 @@
...
+}
+
+function getErrorMessage(xhr) {
+  // Get the specific error message based on status codes or response from server
+  if (xhr.status === 404) {
+    return "The requested resource was not found";
+  } else if (xhr.status === 500) {
+    return "Internal server error occurred.";
+  } else {
+    return "An unknown error occurred.";
```
Comment (FireLemons) [inline app/javascript/src/display_app_metric.js:138]: Could you display an error that states the chart failed to load always and print these specific errors in the console instead?

**Review by FireLemons — CHANGES_REQUESTED** [review]

**Comment by FireLemons** [comment]
You have to get all the checks to pass

**Comment by FireLemons** [comment]
Sometimes rspec and docker will give false failures. For those just make sure the failures aren't related to changes you made

**Comment by FireLemons** [comment]
Made the linter pass and make the error more user friendly
image

**Comment by FireLemons** [comment]
:medal_sports:
