### PR TITLE
Fix: SMS Notification event selection not disabled when notifications are turned off

### LINKED ISSUE #3661: SMS Notification event selection not disabled when notifications are turned off
### Impacted User Types
 - volunteers
 - supervisors
 - admins
 - all casa admins

### Environment

* All

### Current Behavior

* On the edit profile page, the text notification events are not disabled if "Text me" is not pressed

Screen Shot 2022-06-20 at 6 08 28 PM

### Expected Behavior

* If "text me" is not checked, the notification event selection boxes should be disabled

### How to Replicate
ex: 
1. - Log in with any user
2. - Click on "Edit profile"
3. - Uncheck "Text me"

### QA Login Details:
[Link to QA site](https://casa-qa.herokuapp.com/)  

Login Emails: 
- volunteer1@example.com  view site as a volunteer
- supervisor1@example.com view site as a supervisor
- casa_admin1@example.com view site as an admin

password for all users: 12345678

### PR DESCRIPTION
**Pull request by harsohailB**
### What github issue is this PR for, if any?
Resolves #3661 

### What changed, and why?

* Added `require_communication_preference.js` to `application.js`

### How will this affect user permissions?
- Volunteer permissions: n/a
- Supervisor permissions: n/a
- Admin permissions: n/a

### How is this tested? (please write tests!) 💖💪

* System tests to confirm that sms notification event checkboxes are disabled when "Text me" is not selected

### Screenshots please :)

Screen Shot 2022-06-20 at 8 55 47 PM

### CODE REVIEW

File: spec/system/users/edit_spec.rb [hunk 1]
```diff
@@ -99,6 +99,16 @@
...
     end
+
+    it "displays notification events selection as enabled if sms notification preference is selected" do
+      check "user_receive_sms_notifications"
+      expect(page).to have_field("toggle-sms-notification-event", type: "checkbox", disabled: false)
+    end
+
+    it "displays notification events selection as disabled if sms notification preference is not selected" do
+      uncheck "user_receive_sms_notifications"
+      expect(page).to have_field("toggle-sms-notification-event", type: "checkbox", disabled: true)
```
Comment (harsohailB) [inline spec/system/users/edit_spec.rb:110]: This test should be passing but seems like the JS is not running in capybara. Any clues on how to do that?

**Review by xihai01 — APPROVED** [review]
fix tests and it should be good to go
