### PR TITLE
fixes bug that defaults contact made to false

### LINKED ISSUE #673: [BUG] new case contact contact made defaults to false. It should not have a default
[BUG] new case contact contact made defaults to false. It should not have a default
Please also write a test for this to make sure it doesn't break again (for all no-default fields)
This happened while logged into staging with volunteer2

Screen Shot 2020-09-05 at 2 52 57 PM

### PR DESCRIPTION
**Pull request by jmkoni**
### What github issue is this PR for, if any?
Resolves #673

### What changed, and why?
a change was previously made that checked "No" for contact made if `!case_contact.contact_made`. This returns true if `contact_made` is `nil`, so it was effectively defaulting to false. Added back in code and tests that checks if the value is actually set to false. We could potentially simplify this and remove the helper, but that makes it harder to test, so I'm in favor of keeping the helper.

### How will this affect user permissions?
No

### How is this tested? (please write tests!) 💖💪
Added a system spec that validates that, if it's not selected, it doesn't get automatically selected on submit.

### CODE REVIEW

File: app/helpers/case_contacts_helper.rb [hunk 1]
```diff
@@ -8,6 +8,10 @@ def duration_minutes(case_contact)
     case_contact.duration_minutes.to_i.remainder(60)
   end
 
+  def set_contact_made_false(case_contact)
+    case_contact.persisted? && case_contact.contact_made == false
```
Comment (alindeman) [inline app/helpers/case_contacts_helper.rb:12]: Thanks for catching this. The `persisted?` behavior was subtle, so I thought it was unnecessary when I removed it. I was obviously wrong :)

**Review by compwron — APPROVED** [review]
Whew! And excellent tests :) 💖
